// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "feature_extractor_convolve.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic feature_extractor_convolve::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic feature_extractor_convolve::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> feature_extractor_convolve::ap_ST_st1_fsm_0 = "1";
const sc_lv<24> feature_extractor_convolve::ap_ST_st2_fsm_1 = "10";
const sc_lv<24> feature_extractor_convolve::ap_ST_st3_fsm_2 = "100";
const sc_lv<24> feature_extractor_convolve::ap_ST_st4_fsm_3 = "1000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st5_fsm_4 = "10000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st6_fsm_5 = "100000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<24> feature_extractor_convolve::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> feature_extractor_convolve::ap_const_lv1_1 = "1";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_1 = "1";
const sc_lv<1> feature_extractor_convolve::ap_const_lv1_0 = "0";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_2 = "10";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_3 = "11";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_4 = "100";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_5 = "101";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_6 = "110";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_7 = "111";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_D = "1101";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_E = "1110";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_11 = "10001";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_16 = "10110";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_0 = "00000";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_2 = "10";
const sc_lv<3> feature_extractor_convolve::ap_const_lv3_0 = "000";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_17 = "10111";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_10 = "10000";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_12 = "10010";
const sc_lv<32> feature_extractor_convolve::ap_const_lv32_8 = "1000";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_18 = "11000";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_1 = "1";
const sc_lv<2> feature_extractor_convolve::ap_const_lv2_0 = "00";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_1A = "11010";
const sc_lv<5> feature_extractor_convolve::ap_const_lv5_1E = "11110";
const sc_lv<3> feature_extractor_convolve::ap_const_lv3_5 = "101";
const sc_lv<3> feature_extractor_convolve::ap_const_lv3_1 = "1";

feature_extractor_convolve::feature_extractor_convolve(sc_module_name name) : sc_module(name), mVcdFile(0) {
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1 = new feature_extractor_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1");
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->clk(ap_clk);
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->reset(ap_rst);
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->din0(grp_fu_182_p0);
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->din1(grp_fu_182_p1);
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->ce(grp_fu_182_ce);
    feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1->dout(grp_fu_182_p2);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2 = new feature_extractor_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2");
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->clk(ap_clk);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->reset(ap_rst);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->din0(grp_fu_186_p0);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->din1(grp_fu_186_p1);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->ce(grp_fu_186_ce);
    feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2->dout(grp_fu_186_p2);
    feature_extractor_sitofp_32ns_32_6_U3 = new feature_extractor_sitofp_32ns_32_6<1,6,32,32>("feature_extractor_sitofp_32ns_32_6_U3");
    feature_extractor_sitofp_32ns_32_6_U3->clk(ap_clk);
    feature_extractor_sitofp_32ns_32_6_U3->reset(ap_rst);
    feature_extractor_sitofp_32ns_32_6_U3->din0(grp_fu_191_p0);
    feature_extractor_sitofp_32ns_32_6_U3->ce(grp_fu_191_ce);
    feature_extractor_sitofp_32ns_32_6_U3->dout(grp_fu_191_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_36_fu_534_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_37_fu_548_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond3_fu_325_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond3_fu_325_p2 );

    SC_METHOD(thread_ap_sig_bdd_102);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_111);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_125);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_143);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_163);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_178);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_187);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_197);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_206);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_216);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_245);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_258);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_271);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_281);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_187 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_197 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_258 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_206 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_271 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_42 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_216 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_bdd_245 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_102 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_111 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_125 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_143 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_163 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_178 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_281 );

    SC_METHOD(thread_conv_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( conv_addr_1_reg_611 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( tmp_31_fu_320_p1 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_conv_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_conv_d0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_11_reg_692 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );

    SC_METHOD(thread_conv_we0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond4_fu_299_p2 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );

    SC_METHOD(thread_exitcond1_fu_412_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_exitcond2_fu_376_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( j_reg_148 );

    SC_METHOD(thread_exitcond3_fu_325_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_exitcond4_fu_299_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( t_reg_125 );

    SC_METHOD(thread_exitcond5_fu_228_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( s_reg_114 );

    SC_METHOD(thread_exitcond_fu_504_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( l_reg_171 );

    SC_METHOD(thread_grp_fu_182_ce);

    SC_METHOD(thread_grp_fu_182_p0);
    sensitive << ( conv_load_reg_687 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_grp_fu_182_p1);
    sensitive << ( tmp_10_reg_682 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_grp_fu_186_ce);

    SC_METHOD(thread_grp_fu_186_p0);
    sensitive << ( tmp_5_reg_667 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_grp_fu_186_p1);
    sensitive << ( B_q0 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_grp_fu_191_ce);

    SC_METHOD(thread_grp_fu_191_p0);
    sensitive << ( A_load_reg_662 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_i_2_fu_402_p2);
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_j_2_fu_494_p2);
    sensitive << ( j_reg_148 );

    SC_METHOD(thread_k_2_fu_418_p2);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_k_cast4_fu_408_p1);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_l_1_fu_510_p2);
    sensitive << ( l_reg_171 );

    SC_METHOD(thread_l_cast2_fu_500_p1);
    sensitive << ( l_reg_171 );

    SC_METHOD(thread_p_addr10_cast_fu_224_p1);
    sensitive << ( p_addr6_fu_218_p2 );

    SC_METHOD(thread_p_addr10_fu_244_p2);
    sensitive << ( p_addr10_cast_reg_558 );
    sensitive << ( tmp2_trn_cast_fu_240_p1 );

    SC_METHOD(thread_p_addr11_fu_273_p2);
    sensitive << ( p_shl_fu_257_p1 );
    sensitive << ( p_shl1_fu_269_p1 );

    SC_METHOD(thread_p_addr12_fu_315_p2);
    sensitive << ( p_addr11_reg_572 );
    sensitive << ( tmp_9_trn_fu_311_p1 );

    SC_METHOD(thread_p_addr1_cast_fu_530_p1);
    sensitive << ( p_addr1_fu_525_p2 );

    SC_METHOD(thread_p_addr1_fu_525_p2);
    sensitive << ( p_addr_cast_reg_629 );
    sensitive << ( tmp_4_trn_cast_fu_521_p1 );

    SC_METHOD(thread_p_addr2_fu_293_p2);
    sensitive << ( tmp_cast_trn_cast_fu_279_p1 );
    sensitive << ( p_shl9_cast_fu_289_p1 );

    SC_METHOD(thread_p_addr3_cast_fu_472_p1);
    sensitive << ( p_addr3_fu_467_p2 );

    SC_METHOD(thread_p_addr3_fu_467_p2);
    sensitive << ( p_addr2_reg_577 );
    sensitive << ( tmp_3_trn_cast_fu_463_p1 );

    SC_METHOD(thread_p_addr4_fu_488_p2);
    sensitive << ( p_addr3_cast_fu_472_p1 );
    sensitive << ( p_shl4_fu_484_p1 );

    SC_METHOD(thread_p_addr5_fu_543_p2);
    sensitive << ( p_addr4_reg_634 );
    sensitive << ( tmp_8_trn_fu_539_p1 );

    SC_METHOD(thread_p_addr6_fu_218_p2);
    sensitive << ( p_shl_cast_fu_202_p1 );
    sensitive << ( p_shl6_cast_fu_214_p1 );

    SC_METHOD(thread_p_addr7_fu_341_p2);
    sensitive << ( p_addr10_cast_reg_558 );
    sensitive << ( tmp_7_trn_cast_fu_337_p1 );

    SC_METHOD(thread_p_addr8_fu_370_p2);
    sensitive << ( p_shl2_fu_354_p1 );
    sensitive << ( p_shl3_fu_366_p1 );

    SC_METHOD(thread_p_addr9_fu_392_p2);
    sensitive << ( p_addr8_reg_598 );
    sensitive << ( tmp_1_trn_fu_388_p1 );

    SC_METHOD(thread_p_addr_cast_fu_459_p1);
    sensitive << ( p_addr_fu_453_p2 );

    SC_METHOD(thread_p_addr_fu_453_p2);
    sensitive << ( p_shl14_cast_fu_437_p1 );
    sensitive << ( p_shl15_cast_fu_449_p1 );

    SC_METHOD(thread_p_shl14_cast_fu_437_p1);
    sensitive << ( tmp_33_fu_429_p3 );

    SC_METHOD(thread_p_shl15_cast_fu_449_p1);
    sensitive << ( tmp_34_fu_441_p3 );

    SC_METHOD(thread_p_shl1_fu_269_p1);
    sensitive << ( tmp_28_fu_261_p3 );

    SC_METHOD(thread_p_shl2_fu_354_p1);
    sensitive << ( tmp_29_fu_346_p3 );

    SC_METHOD(thread_p_shl3_fu_366_p1);
    sensitive << ( tmp_30_fu_358_p3 );

    SC_METHOD(thread_p_shl4_fu_484_p1);
    sensitive << ( tmp_35_fu_476_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_214_p1);
    sensitive << ( tmp_25_fu_206_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_289_p1);
    sensitive << ( tmp_26_fu_282_p3 );

    SC_METHOD(thread_p_shl_cast_fu_202_p1);
    sensitive << ( tmp_24_fu_194_p3 );

    SC_METHOD(thread_p_shl_fu_257_p1);
    sensitive << ( tmp_27_fu_249_p3 );

    SC_METHOD(thread_s_1_fu_234_p2);
    sensitive << ( s_reg_114 );

    SC_METHOD(thread_t_1_fu_305_p2);
    sensitive << ( t_reg_125 );

    SC_METHOD(thread_tmp2_trn_cast_fu_240_p1);
    sensitive << ( s_reg_114 );

    SC_METHOD(thread_tmp_1_trn_fu_388_p1);
    sensitive << ( tmp_s_fu_382_p2 );

    SC_METHOD(thread_tmp_24_fu_194_p3);
    sensitive << ( tmp1 );

    SC_METHOD(thread_tmp_25_fu_206_p3);
    sensitive << ( tmp1 );

    SC_METHOD(thread_tmp_26_fu_282_p3);
    sensitive << ( tmp );

    SC_METHOD(thread_tmp_27_fu_249_p3);
    sensitive << ( p_addr10_fu_244_p2 );

    SC_METHOD(thread_tmp_28_fu_261_p3);
    sensitive << ( p_addr10_fu_244_p2 );

    SC_METHOD(thread_tmp_29_fu_346_p3);
    sensitive << ( p_addr7_fu_341_p2 );

    SC_METHOD(thread_tmp_30_fu_358_p3);
    sensitive << ( p_addr7_fu_341_p2 );

    SC_METHOD(thread_tmp_31_fu_320_p1);
    sensitive << ( p_addr12_fu_315_p2 );

    SC_METHOD(thread_tmp_32_fu_397_p1);
    sensitive << ( p_addr9_fu_392_p2 );

    SC_METHOD(thread_tmp_33_fu_429_p3);
    sensitive << ( x_fu_424_p2 );

    SC_METHOD(thread_tmp_34_fu_441_p3);
    sensitive << ( x_fu_424_p2 );

    SC_METHOD(thread_tmp_35_fu_476_p3);
    sensitive << ( p_addr3_fu_467_p2 );

    SC_METHOD(thread_tmp_36_fu_534_p1);
    sensitive << ( p_addr1_cast_fu_530_p1 );

    SC_METHOD(thread_tmp_37_fu_548_p1);
    sensitive << ( p_addr5_reg_657 );

    SC_METHOD(thread_tmp_3_trn_cast_fu_463_p1);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_tmp_4_trn_cast_fu_521_p1);
    sensitive << ( y_fu_516_p2 );

    SC_METHOD(thread_tmp_6_fu_331_p2);
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_tmp_7_trn_cast_fu_337_p1);
    sensitive << ( tmp_6_fu_331_p2 );

    SC_METHOD(thread_tmp_8_trn_fu_539_p1);
    sensitive << ( l_reg_171 );

    SC_METHOD(thread_tmp_9_trn_fu_311_p1);
    sensitive << ( t_reg_125 );

    SC_METHOD(thread_tmp_cast_trn_cast_fu_279_p1);
    sensitive << ( tmp );

    SC_METHOD(thread_tmp_s_fu_382_p2);
    sensitive << ( j_reg_148 );

    SC_METHOD(thread_x_fu_424_p2);
    sensitive << ( tmp_6_reg_593 );
    sensitive << ( k_cast4_fu_408_p1 );

    SC_METHOD(thread_y_fu_516_p2);
    sensitive << ( tmp_s_reg_606 );
    sensitive << ( l_cast2_fu_500_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_228_p2 );
    sensitive << ( exitcond3_fu_325_p2 );
    sensitive << ( exitcond2_fu_376_p2 );
    sensitive << ( exitcond1_fu_412_p2 );
    sensitive << ( exitcond_fu_504_p2 );
    sensitive << ( exitcond4_fu_299_p2 );

    ap_CS_fsm = "000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "feature_extractor_convolve_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, tmp, "(port)tmp");
    sc_trace(mVcdFile, conv_address0, "(port)conv_address0");
    sc_trace(mVcdFile, conv_ce0, "(port)conv_ce0");
    sc_trace(mVcdFile, conv_we0, "(port)conv_we0");
    sc_trace(mVcdFile, conv_d0, "(port)conv_d0");
    sc_trace(mVcdFile, conv_q0, "(port)conv_q0");
    sc_trace(mVcdFile, tmp1, "(port)tmp1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_42, "ap_sig_bdd_42");
    sc_trace(mVcdFile, p_addr10_cast_fu_224_p1, "p_addr10_cast_fu_224_p1");
    sc_trace(mVcdFile, p_addr10_cast_reg_558, "p_addr10_cast_reg_558");
    sc_trace(mVcdFile, s_1_fu_234_p2, "s_1_fu_234_p2");
    sc_trace(mVcdFile, s_1_reg_567, "s_1_reg_567");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_83, "ap_sig_bdd_83");
    sc_trace(mVcdFile, p_addr11_fu_273_p2, "p_addr11_fu_273_p2");
    sc_trace(mVcdFile, p_addr11_reg_572, "p_addr11_reg_572");
    sc_trace(mVcdFile, exitcond5_fu_228_p2, "exitcond5_fu_228_p2");
    sc_trace(mVcdFile, p_addr2_fu_293_p2, "p_addr2_fu_293_p2");
    sc_trace(mVcdFile, p_addr2_reg_577, "p_addr2_reg_577");
    sc_trace(mVcdFile, t_1_fu_305_p2, "t_1_fu_305_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_102, "ap_sig_bdd_102");
    sc_trace(mVcdFile, tmp_6_fu_331_p2, "tmp_6_fu_331_p2");
    sc_trace(mVcdFile, tmp_6_reg_593, "tmp_6_reg_593");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_111, "ap_sig_bdd_111");
    sc_trace(mVcdFile, exitcond3_fu_325_p2, "exitcond3_fu_325_p2");
    sc_trace(mVcdFile, p_addr8_fu_370_p2, "p_addr8_fu_370_p2");
    sc_trace(mVcdFile, p_addr8_reg_598, "p_addr8_reg_598");
    sc_trace(mVcdFile, tmp_s_fu_382_p2, "tmp_s_fu_382_p2");
    sc_trace(mVcdFile, tmp_s_reg_606, "tmp_s_reg_606");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_125, "ap_sig_bdd_125");
    sc_trace(mVcdFile, exitcond2_fu_376_p2, "exitcond2_fu_376_p2");
    sc_trace(mVcdFile, conv_addr_1_reg_611, "conv_addr_1_reg_611");
    sc_trace(mVcdFile, i_2_fu_402_p2, "i_2_fu_402_p2");
    sc_trace(mVcdFile, k_2_fu_418_p2, "k_2_fu_418_p2");
    sc_trace(mVcdFile, k_2_reg_624, "k_2_reg_624");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_143, "ap_sig_bdd_143");
    sc_trace(mVcdFile, p_addr_cast_fu_459_p1, "p_addr_cast_fu_459_p1");
    sc_trace(mVcdFile, p_addr_cast_reg_629, "p_addr_cast_reg_629");
    sc_trace(mVcdFile, exitcond1_fu_412_p2, "exitcond1_fu_412_p2");
    sc_trace(mVcdFile, p_addr4_fu_488_p2, "p_addr4_fu_488_p2");
    sc_trace(mVcdFile, p_addr4_reg_634, "p_addr4_reg_634");
    sc_trace(mVcdFile, j_2_fu_494_p2, "j_2_fu_494_p2");
    sc_trace(mVcdFile, l_1_fu_510_p2, "l_1_fu_510_p2");
    sc_trace(mVcdFile, l_1_reg_647, "l_1_reg_647");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_163, "ap_sig_bdd_163");
    sc_trace(mVcdFile, exitcond_fu_504_p2, "exitcond_fu_504_p2");
    sc_trace(mVcdFile, p_addr5_fu_543_p2, "p_addr5_fu_543_p2");
    sc_trace(mVcdFile, p_addr5_reg_657, "p_addr5_reg_657");
    sc_trace(mVcdFile, A_load_reg_662, "A_load_reg_662");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_178, "ap_sig_bdd_178");
    sc_trace(mVcdFile, grp_fu_191_p1, "grp_fu_191_p1");
    sc_trace(mVcdFile, tmp_5_reg_667, "tmp_5_reg_667");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_187, "ap_sig_bdd_187");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_197, "ap_sig_bdd_197");
    sc_trace(mVcdFile, grp_fu_186_p2, "grp_fu_186_p2");
    sc_trace(mVcdFile, tmp_10_reg_682, "tmp_10_reg_682");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_206, "ap_sig_bdd_206");
    sc_trace(mVcdFile, conv_load_reg_687, "conv_load_reg_687");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, tmp_11_reg_692, "tmp_11_reg_692");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_216, "ap_sig_bdd_216");
    sc_trace(mVcdFile, s_reg_114, "s_reg_114");
    sc_trace(mVcdFile, exitcond4_fu_299_p2, "exitcond4_fu_299_p2");
    sc_trace(mVcdFile, t_reg_125, "t_reg_125");
    sc_trace(mVcdFile, i_reg_136, "i_reg_136");
    sc_trace(mVcdFile, j_reg_148, "j_reg_148");
    sc_trace(mVcdFile, k_reg_160, "k_reg_160");
    sc_trace(mVcdFile, l_reg_171, "l_reg_171");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_bdd_245, "ap_sig_bdd_245");
    sc_trace(mVcdFile, tmp_31_fu_320_p1, "tmp_31_fu_320_p1");
    sc_trace(mVcdFile, tmp_32_fu_397_p1, "tmp_32_fu_397_p1");
    sc_trace(mVcdFile, tmp_36_fu_534_p1, "tmp_36_fu_534_p1");
    sc_trace(mVcdFile, tmp_37_fu_548_p1, "tmp_37_fu_548_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_258, "ap_sig_bdd_258");
    sc_trace(mVcdFile, grp_fu_182_p0, "grp_fu_182_p0");
    sc_trace(mVcdFile, grp_fu_182_p1, "grp_fu_182_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_271, "ap_sig_bdd_271");
    sc_trace(mVcdFile, grp_fu_186_p0, "grp_fu_186_p0");
    sc_trace(mVcdFile, grp_fu_186_p1, "grp_fu_186_p1");
    sc_trace(mVcdFile, grp_fu_191_p0, "grp_fu_191_p0");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_281, "ap_sig_bdd_281");
    sc_trace(mVcdFile, tmp_24_fu_194_p3, "tmp_24_fu_194_p3");
    sc_trace(mVcdFile, tmp_25_fu_206_p3, "tmp_25_fu_206_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_202_p1, "p_shl_cast_fu_202_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_214_p1, "p_shl6_cast_fu_214_p1");
    sc_trace(mVcdFile, p_addr6_fu_218_p2, "p_addr6_fu_218_p2");
    sc_trace(mVcdFile, tmp2_trn_cast_fu_240_p1, "tmp2_trn_cast_fu_240_p1");
    sc_trace(mVcdFile, p_addr10_fu_244_p2, "p_addr10_fu_244_p2");
    sc_trace(mVcdFile, tmp_27_fu_249_p3, "tmp_27_fu_249_p3");
    sc_trace(mVcdFile, tmp_28_fu_261_p3, "tmp_28_fu_261_p3");
    sc_trace(mVcdFile, p_shl_fu_257_p1, "p_shl_fu_257_p1");
    sc_trace(mVcdFile, p_shl1_fu_269_p1, "p_shl1_fu_269_p1");
    sc_trace(mVcdFile, tmp_26_fu_282_p3, "tmp_26_fu_282_p3");
    sc_trace(mVcdFile, tmp_cast_trn_cast_fu_279_p1, "tmp_cast_trn_cast_fu_279_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_289_p1, "p_shl9_cast_fu_289_p1");
    sc_trace(mVcdFile, tmp_9_trn_fu_311_p1, "tmp_9_trn_fu_311_p1");
    sc_trace(mVcdFile, p_addr12_fu_315_p2, "p_addr12_fu_315_p2");
    sc_trace(mVcdFile, tmp_7_trn_cast_fu_337_p1, "tmp_7_trn_cast_fu_337_p1");
    sc_trace(mVcdFile, p_addr7_fu_341_p2, "p_addr7_fu_341_p2");
    sc_trace(mVcdFile, tmp_29_fu_346_p3, "tmp_29_fu_346_p3");
    sc_trace(mVcdFile, tmp_30_fu_358_p3, "tmp_30_fu_358_p3");
    sc_trace(mVcdFile, p_shl2_fu_354_p1, "p_shl2_fu_354_p1");
    sc_trace(mVcdFile, p_shl3_fu_366_p1, "p_shl3_fu_366_p1");
    sc_trace(mVcdFile, tmp_1_trn_fu_388_p1, "tmp_1_trn_fu_388_p1");
    sc_trace(mVcdFile, p_addr9_fu_392_p2, "p_addr9_fu_392_p2");
    sc_trace(mVcdFile, k_cast4_fu_408_p1, "k_cast4_fu_408_p1");
    sc_trace(mVcdFile, x_fu_424_p2, "x_fu_424_p2");
    sc_trace(mVcdFile, tmp_33_fu_429_p3, "tmp_33_fu_429_p3");
    sc_trace(mVcdFile, tmp_34_fu_441_p3, "tmp_34_fu_441_p3");
    sc_trace(mVcdFile, p_shl14_cast_fu_437_p1, "p_shl14_cast_fu_437_p1");
    sc_trace(mVcdFile, p_shl15_cast_fu_449_p1, "p_shl15_cast_fu_449_p1");
    sc_trace(mVcdFile, p_addr_fu_453_p2, "p_addr_fu_453_p2");
    sc_trace(mVcdFile, tmp_3_trn_cast_fu_463_p1, "tmp_3_trn_cast_fu_463_p1");
    sc_trace(mVcdFile, p_addr3_fu_467_p2, "p_addr3_fu_467_p2");
    sc_trace(mVcdFile, tmp_35_fu_476_p3, "tmp_35_fu_476_p3");
    sc_trace(mVcdFile, p_addr3_cast_fu_472_p1, "p_addr3_cast_fu_472_p1");
    sc_trace(mVcdFile, p_shl4_fu_484_p1, "p_shl4_fu_484_p1");
    sc_trace(mVcdFile, l_cast2_fu_500_p1, "l_cast2_fu_500_p1");
    sc_trace(mVcdFile, y_fu_516_p2, "y_fu_516_p2");
    sc_trace(mVcdFile, tmp_4_trn_cast_fu_521_p1, "tmp_4_trn_cast_fu_521_p1");
    sc_trace(mVcdFile, p_addr1_fu_525_p2, "p_addr1_fu_525_p2");
    sc_trace(mVcdFile, p_addr1_cast_fu_530_p1, "p_addr1_cast_fu_530_p1");
    sc_trace(mVcdFile, tmp_8_trn_fu_539_p1, "tmp_8_trn_fu_539_p1");
    sc_trace(mVcdFile, grp_fu_182_ce, "grp_fu_182_ce");
    sc_trace(mVcdFile, grp_fu_186_ce, "grp_fu_186_ce");
    sc_trace(mVcdFile, grp_fu_191_ce, "grp_fu_191_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

feature_extractor_convolve::~feature_extractor_convolve() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete feature_extractor_fadd_32ns_32ns_32_5_full_dsp_U1;
    delete feature_extractor_fmul_32ns_32ns_32_4_max_dsp_U2;
    delete feature_extractor_sitofp_32ns_32_6_U3;
}

void feature_extractor_convolve::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_fu_228_p2.read(), ap_const_lv1_0))) {
        i_reg_136 = ap_const_lv5_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_376_p2.read()))) {
        i_reg_136 = i_2_fu_402_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_325_p2.read()))) {
        j_reg_148 = ap_const_lv5_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        j_reg_148 = j_2_fu_494_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_504_p2.read()))) {
        k_reg_160 = k_2_reg_624.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_376_p2.read()))) {
        k_reg_160 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        l_reg_171 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        l_reg_171 = l_1_reg_647.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_299_p2.read()))) {
        s_reg_114 = s_1_reg_567.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        s_reg_114 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_228_p2.read(), ap_const_lv1_0))) {
        t_reg_125 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_299_p2.read()))) {
        t_reg_125 = t_1_fu_305_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        A_load_reg_662 = A_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_376_p2.read()))) {
        conv_addr_1_reg_611 =  (sc_lv<12>) (tmp_32_fu_397_p1.read());
        tmp_s_reg_606 = tmp_s_fu_382_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        conv_load_reg_687 = conv_q0.read();
        tmp_10_reg_682 = grp_fu_186_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        k_2_reg_624 = k_2_fu_418_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        l_1_reg_647 = l_1_fu_510_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_addr10_cast_reg_558 = p_addr10_cast_fu_224_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond5_fu_228_p2.read(), ap_const_lv1_0))) {
        p_addr11_reg_572 = p_addr11_fu_273_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(exitcond5_fu_228_p2.read(), ap_const_lv1_0))) {
        p_addr2_reg_577 = p_addr2_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read()))) {
        p_addr4_reg_634 = p_addr4_fu_488_p2.read();
        p_addr_cast_reg_629 = p_addr_cast_fu_459_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_504_p2.read()))) {
        p_addr5_reg_657 = p_addr5_fu_543_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_325_p2.read()))) {
        p_addr8_reg_598 = p_addr8_fu_370_p2.read();
        tmp_6_reg_593 = tmp_6_fu_331_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        s_1_reg_567 = s_1_fu_234_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        tmp_11_reg_692 = grp_fu_182_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        tmp_5_reg_667 = grp_fu_191_p1.read();
    }
}

void feature_extractor_convolve::thread_A_address0() {
    A_address0 =  (sc_lv<10>) (tmp_36_fu_534_p1.read());
}

void feature_extractor_convolve::thread_A_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_B_address0() {
    B_address0 =  (sc_lv<8>) (tmp_37_fu_548_p1.read());
}

void feature_extractor_convolve::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_325_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_325_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_bdd_102() {
    ap_sig_bdd_102 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void feature_extractor_convolve::thread_ap_sig_bdd_111() {
    ap_sig_bdd_111 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void feature_extractor_convolve::thread_ap_sig_bdd_125() {
    ap_sig_bdd_125 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void feature_extractor_convolve::thread_ap_sig_bdd_143() {
    ap_sig_bdd_143 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void feature_extractor_convolve::thread_ap_sig_bdd_163() {
    ap_sig_bdd_163 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void feature_extractor_convolve::thread_ap_sig_bdd_178() {
    ap_sig_bdd_178 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void feature_extractor_convolve::thread_ap_sig_bdd_187() {
    ap_sig_bdd_187 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void feature_extractor_convolve::thread_ap_sig_bdd_197() {
    ap_sig_bdd_197 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void feature_extractor_convolve::thread_ap_sig_bdd_206() {
    ap_sig_bdd_206 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void feature_extractor_convolve::thread_ap_sig_bdd_216() {
    ap_sig_bdd_216 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void feature_extractor_convolve::thread_ap_sig_bdd_245() {
    ap_sig_bdd_245 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void feature_extractor_convolve::thread_ap_sig_bdd_258() {
    ap_sig_bdd_258 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void feature_extractor_convolve::thread_ap_sig_bdd_271() {
    ap_sig_bdd_271 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void feature_extractor_convolve::thread_ap_sig_bdd_281() {
    ap_sig_bdd_281 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void feature_extractor_convolve::thread_ap_sig_bdd_42() {
    ap_sig_bdd_42 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void feature_extractor_convolve::thread_ap_sig_bdd_83() {
    ap_sig_bdd_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_187.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_197.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_258.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_206.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_271.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_42.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_216.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_bdd_245.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_83.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_102.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_111.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_125.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_143.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_163.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_178.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_281.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_conv_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        conv_address0 =  (sc_lv<12>) (tmp_31_fu_320_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        conv_address0 = conv_addr_1_reg_611.read();
    } else {
        conv_address0 = "XXXXXXXXXXXX";
    }
}

void feature_extractor_convolve::thread_conv_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        conv_ce0 = ap_const_logic_1;
    } else {
        conv_ce0 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_conv_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        conv_d0 = tmp_11_reg_692.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        conv_d0 = ap_const_lv32_0;
    } else {
        conv_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void feature_extractor_convolve::thread_conv_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_299_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()))) {
        conv_we0 = ap_const_logic_1;
    } else {
        conv_we0 = ap_const_logic_0;
    }
}

void feature_extractor_convolve::thread_exitcond1_fu_412_p2() {
    exitcond1_fu_412_p2 = (!k_reg_160.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_160.read() == ap_const_lv3_5);
}

void feature_extractor_convolve::thread_exitcond2_fu_376_p2() {
    exitcond2_fu_376_p2 = (!j_reg_148.read().is_01() || !ap_const_lv5_1A.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_148.read() == ap_const_lv5_1A);
}

void feature_extractor_convolve::thread_exitcond3_fu_325_p2() {
    exitcond3_fu_325_p2 = (!i_reg_136.read().is_01() || !ap_const_lv5_1A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_136.read() == ap_const_lv5_1A);
}

void feature_extractor_convolve::thread_exitcond4_fu_299_p2() {
    exitcond4_fu_299_p2 = (!t_reg_125.read().is_01() || !ap_const_lv5_18.is_01())? sc_lv<1>(): sc_lv<1>(t_reg_125.read() == ap_const_lv5_18);
}

void feature_extractor_convolve::thread_exitcond5_fu_228_p2() {
    exitcond5_fu_228_p2 = (!s_reg_114.read().is_01() || !ap_const_lv5_18.is_01())? sc_lv<1>(): sc_lv<1>(s_reg_114.read() == ap_const_lv5_18);
}

void feature_extractor_convolve::thread_exitcond_fu_504_p2() {
    exitcond_fu_504_p2 = (!l_reg_171.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(l_reg_171.read() == ap_const_lv3_5);
}

void feature_extractor_convolve::thread_grp_fu_182_ce() {
    grp_fu_182_ce = ap_const_logic_1;
}

void feature_extractor_convolve::thread_grp_fu_182_p0() {
    grp_fu_182_p0 = conv_load_reg_687.read();
}

void feature_extractor_convolve::thread_grp_fu_182_p1() {
    grp_fu_182_p1 = tmp_10_reg_682.read();
}

void feature_extractor_convolve::thread_grp_fu_186_ce() {
    grp_fu_186_ce = ap_const_logic_1;
}

void feature_extractor_convolve::thread_grp_fu_186_p0() {
    grp_fu_186_p0 = tmp_5_reg_667.read();
}

void feature_extractor_convolve::thread_grp_fu_186_p1() {
    grp_fu_186_p1 = B_q0.read();
}

void feature_extractor_convolve::thread_grp_fu_191_ce() {
    grp_fu_191_ce = ap_const_logic_1;
}

void feature_extractor_convolve::thread_grp_fu_191_p0() {
    grp_fu_191_p0 = A_load_reg_662.read();
}

void feature_extractor_convolve::thread_i_2_fu_402_p2() {
    i_2_fu_402_p2 = (!i_reg_136.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_136.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void feature_extractor_convolve::thread_j_2_fu_494_p2() {
    j_2_fu_494_p2 = (!j_reg_148.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_reg_148.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void feature_extractor_convolve::thread_k_2_fu_418_p2() {
    k_2_fu_418_p2 = (!k_reg_160.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_reg_160.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void feature_extractor_convolve::thread_k_cast4_fu_408_p1() {
    k_cast4_fu_408_p1 = esl_zext<5,3>(k_reg_160.read());
}

void feature_extractor_convolve::thread_l_1_fu_510_p2() {
    l_1_fu_510_p2 = (!l_reg_171.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(l_reg_171.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void feature_extractor_convolve::thread_l_cast2_fu_500_p1() {
    l_cast2_fu_500_p1 = esl_zext<5,3>(l_reg_171.read());
}

void feature_extractor_convolve::thread_p_addr10_cast_fu_224_p1() {
    p_addr10_cast_fu_224_p1 = esl_sext<10,9>(p_addr6_fu_218_p2.read());
}

void feature_extractor_convolve::thread_p_addr10_fu_244_p2() {
    p_addr10_fu_244_p2 = (!p_addr10_cast_reg_558.read().is_01() || !tmp2_trn_cast_fu_240_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(p_addr10_cast_reg_558.read()) + sc_biguint<10>(tmp2_trn_cast_fu_240_p1.read()));
}

void feature_extractor_convolve::thread_p_addr11_fu_273_p2() {
    p_addr11_fu_273_p2 = (!p_shl_fu_257_p1.read().is_01() || !p_shl1_fu_269_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_shl_fu_257_p1.read()) - sc_bigint<32>(p_shl1_fu_269_p1.read()));
}

void feature_extractor_convolve::thread_p_addr12_fu_315_p2() {
    p_addr12_fu_315_p2 = (!p_addr11_reg_572.read().is_01() || !tmp_9_trn_fu_311_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_addr11_reg_572.read()) + sc_biguint<32>(tmp_9_trn_fu_311_p1.read()));
}

void feature_extractor_convolve::thread_p_addr1_cast_fu_530_p1() {
    p_addr1_cast_fu_530_p1 = esl_sext<32,12>(p_addr1_fu_525_p2.read());
}

void feature_extractor_convolve::thread_p_addr1_fu_525_p2() {
    p_addr1_fu_525_p2 = (!tmp_4_trn_cast_fu_521_p1.read().is_01() || !p_addr_cast_reg_629.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_4_trn_cast_fu_521_p1.read()) + sc_bigint<12>(p_addr_cast_reg_629.read()));
}

void feature_extractor_convolve::thread_p_addr2_fu_293_p2() {
    p_addr2_fu_293_p2 = (!tmp_cast_trn_cast_fu_279_p1.read().is_01() || !p_shl9_cast_fu_289_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_cast_trn_cast_fu_279_p1.read()) + sc_biguint<6>(p_shl9_cast_fu_289_p1.read()));
}

void feature_extractor_convolve::thread_p_addr3_cast_fu_472_p1() {
    p_addr3_cast_fu_472_p1 = esl_zext<32,6>(p_addr3_fu_467_p2.read());
}

void feature_extractor_convolve::thread_p_addr3_fu_467_p2() {
    p_addr3_fu_467_p2 = (!p_addr2_reg_577.read().is_01() || !tmp_3_trn_cast_fu_463_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(p_addr2_reg_577.read()) + sc_biguint<6>(tmp_3_trn_cast_fu_463_p1.read()));
}

void feature_extractor_convolve::thread_p_addr4_fu_488_p2() {
    p_addr4_fu_488_p2 = (!p_addr3_cast_fu_472_p1.read().is_01() || !p_shl4_fu_484_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_addr3_cast_fu_472_p1.read()) + sc_biguint<32>(p_shl4_fu_484_p1.read()));
}

void feature_extractor_convolve::thread_p_addr5_fu_543_p2() {
    p_addr5_fu_543_p2 = (!tmp_8_trn_fu_539_p1.read().is_01() || !p_addr4_reg_634.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_8_trn_fu_539_p1.read()) + sc_biguint<32>(p_addr4_reg_634.read()));
}

void feature_extractor_convolve::thread_p_addr6_fu_218_p2() {
    p_addr6_fu_218_p2 = (!p_shl_cast_fu_202_p1.read().is_01() || !p_shl6_cast_fu_214_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl_cast_fu_202_p1.read()) - sc_biguint<9>(p_shl6_cast_fu_214_p1.read()));
}

void feature_extractor_convolve::thread_p_addr7_fu_341_p2() {
    p_addr7_fu_341_p2 = (!p_addr10_cast_reg_558.read().is_01() || !tmp_7_trn_cast_fu_337_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(p_addr10_cast_reg_558.read()) + sc_biguint<10>(tmp_7_trn_cast_fu_337_p1.read()));
}

void feature_extractor_convolve::thread_p_addr8_fu_370_p2() {
    p_addr8_fu_370_p2 = (!p_shl2_fu_354_p1.read().is_01() || !p_shl3_fu_366_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_shl2_fu_354_p1.read()) - sc_bigint<32>(p_shl3_fu_366_p1.read()));
}

void feature_extractor_convolve::thread_p_addr9_fu_392_p2() {
    p_addr9_fu_392_p2 = (!p_addr8_reg_598.read().is_01() || !tmp_1_trn_fu_388_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_addr8_reg_598.read()) + sc_biguint<32>(tmp_1_trn_fu_388_p1.read()));
}

void feature_extractor_convolve::thread_p_addr_cast_fu_459_p1() {
    p_addr_cast_fu_459_p1 = esl_sext<12,11>(p_addr_fu_453_p2.read());
}

void feature_extractor_convolve::thread_p_addr_fu_453_p2() {
    p_addr_fu_453_p2 = (!p_shl14_cast_fu_437_p1.read().is_01() || !p_shl15_cast_fu_449_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl14_cast_fu_437_p1.read()) - sc_biguint<11>(p_shl15_cast_fu_449_p1.read()));
}

void feature_extractor_convolve::thread_p_shl14_cast_fu_437_p1() {
    p_shl14_cast_fu_437_p1 = esl_zext<11,10>(tmp_33_fu_429_p3.read());
}

void feature_extractor_convolve::thread_p_shl15_cast_fu_449_p1() {
    p_shl15_cast_fu_449_p1 = esl_zext<11,7>(tmp_34_fu_441_p3.read());
}

void feature_extractor_convolve::thread_p_shl1_fu_269_p1() {
    p_shl1_fu_269_p1 = esl_sext<32,13>(tmp_28_fu_261_p3.read());
}

void feature_extractor_convolve::thread_p_shl2_fu_354_p1() {
    p_shl2_fu_354_p1 = esl_sext<32,15>(tmp_29_fu_346_p3.read());
}

void feature_extractor_convolve::thread_p_shl3_fu_366_p1() {
    p_shl3_fu_366_p1 = esl_sext<32,13>(tmp_30_fu_358_p3.read());
}

void feature_extractor_convolve::thread_p_shl4_fu_484_p1() {
    p_shl4_fu_484_p1 = esl_zext<32,8>(tmp_35_fu_476_p3.read());
}

void feature_extractor_convolve::thread_p_shl6_cast_fu_214_p1() {
    p_shl6_cast_fu_214_p1 = esl_zext<9,6>(tmp_25_fu_206_p3.read());
}

void feature_extractor_convolve::thread_p_shl9_cast_fu_289_p1() {
    p_shl9_cast_fu_289_p1 = esl_zext<6,5>(tmp_26_fu_282_p3.read());
}

void feature_extractor_convolve::thread_p_shl_cast_fu_202_p1() {
    p_shl_cast_fu_202_p1 = esl_zext<9,8>(tmp_24_fu_194_p3.read());
}

void feature_extractor_convolve::thread_p_shl_fu_257_p1() {
    p_shl_fu_257_p1 = esl_sext<32,15>(tmp_27_fu_249_p3.read());
}

void feature_extractor_convolve::thread_s_1_fu_234_p2() {
    s_1_fu_234_p2 = (!s_reg_114.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(s_reg_114.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void feature_extractor_convolve::thread_t_1_fu_305_p2() {
    t_1_fu_305_p2 = (!t_reg_125.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(t_reg_125.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void feature_extractor_convolve::thread_tmp2_trn_cast_fu_240_p1() {
    tmp2_trn_cast_fu_240_p1 = esl_zext<10,5>(s_reg_114.read());
}

void feature_extractor_convolve::thread_tmp_1_trn_fu_388_p1() {
    tmp_1_trn_fu_388_p1 = esl_zext<32,5>(tmp_s_fu_382_p2.read());
}

void feature_extractor_convolve::thread_tmp_24_fu_194_p3() {
    tmp_24_fu_194_p3 = esl_concat<3,5>(tmp1.read(), ap_const_lv5_0);
}

void feature_extractor_convolve::thread_tmp_25_fu_206_p3() {
    tmp_25_fu_206_p3 = esl_concat<3,3>(tmp1.read(), ap_const_lv3_0);
}

void feature_extractor_convolve::thread_tmp_26_fu_282_p3() {
    tmp_26_fu_282_p3 = esl_concat<3,2>(tmp.read(), ap_const_lv2_0);
}

void feature_extractor_convolve::thread_tmp_27_fu_249_p3() {
    tmp_27_fu_249_p3 = esl_concat<10,5>(p_addr10_fu_244_p2.read(), ap_const_lv5_0);
}

void feature_extractor_convolve::thread_tmp_28_fu_261_p3() {
    tmp_28_fu_261_p3 = esl_concat<10,3>(p_addr10_fu_244_p2.read(), ap_const_lv3_0);
}

void feature_extractor_convolve::thread_tmp_29_fu_346_p3() {
    tmp_29_fu_346_p3 = esl_concat<10,5>(p_addr7_fu_341_p2.read(), ap_const_lv5_0);
}

void feature_extractor_convolve::thread_tmp_30_fu_358_p3() {
    tmp_30_fu_358_p3 = esl_concat<10,3>(p_addr7_fu_341_p2.read(), ap_const_lv3_0);
}

void feature_extractor_convolve::thread_tmp_31_fu_320_p1() {
    tmp_31_fu_320_p1 = esl_zext<64,32>(p_addr12_fu_315_p2.read());
}

void feature_extractor_convolve::thread_tmp_32_fu_397_p1() {
    tmp_32_fu_397_p1 = esl_zext<64,32>(p_addr9_fu_392_p2.read());
}

void feature_extractor_convolve::thread_tmp_33_fu_429_p3() {
    tmp_33_fu_429_p3 = esl_concat<5,5>(x_fu_424_p2.read(), ap_const_lv5_0);
}

void feature_extractor_convolve::thread_tmp_34_fu_441_p3() {
    tmp_34_fu_441_p3 = esl_concat<5,2>(x_fu_424_p2.read(), ap_const_lv2_0);
}

void feature_extractor_convolve::thread_tmp_35_fu_476_p3() {
    tmp_35_fu_476_p3 = esl_concat<6,2>(p_addr3_fu_467_p2.read(), ap_const_lv2_0);
}

void feature_extractor_convolve::thread_tmp_36_fu_534_p1() {
    tmp_36_fu_534_p1 = esl_zext<64,32>(p_addr1_cast_fu_530_p1.read());
}

void feature_extractor_convolve::thread_tmp_37_fu_548_p1() {
    tmp_37_fu_548_p1 = esl_zext<64,32>(p_addr5_reg_657.read());
}

void feature_extractor_convolve::thread_tmp_3_trn_cast_fu_463_p1() {
    tmp_3_trn_cast_fu_463_p1 = esl_zext<6,3>(k_reg_160.read());
}

void feature_extractor_convolve::thread_tmp_4_trn_cast_fu_521_p1() {
    tmp_4_trn_cast_fu_521_p1 = esl_zext<12,5>(y_fu_516_p2.read());
}

void feature_extractor_convolve::thread_tmp_6_fu_331_p2() {
    tmp_6_fu_331_p2 = (!i_reg_136.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_136.read()) + sc_bigint<5>(ap_const_lv5_1E));
}

void feature_extractor_convolve::thread_tmp_7_trn_cast_fu_337_p1() {
    tmp_7_trn_cast_fu_337_p1 = esl_zext<10,5>(tmp_6_fu_331_p2.read());
}

void feature_extractor_convolve::thread_tmp_8_trn_fu_539_p1() {
    tmp_8_trn_fu_539_p1 = esl_zext<32,3>(l_reg_171.read());
}

void feature_extractor_convolve::thread_tmp_9_trn_fu_311_p1() {
    tmp_9_trn_fu_311_p1 = esl_zext<32,5>(t_reg_125.read());
}

void feature_extractor_convolve::thread_tmp_cast_trn_cast_fu_279_p1() {
    tmp_cast_trn_cast_fu_279_p1 = esl_zext<6,3>(tmp.read());
}

void feature_extractor_convolve::thread_tmp_s_fu_382_p2() {
    tmp_s_fu_382_p2 = (!j_reg_148.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<5>(): (sc_biguint<5>(j_reg_148.read()) + sc_bigint<5>(ap_const_lv5_1E));
}

void feature_extractor_convolve::thread_x_fu_424_p2() {
    x_fu_424_p2 = (!k_cast4_fu_408_p1.read().is_01() || !tmp_6_reg_593.read().is_01())? sc_lv<5>(): (sc_biguint<5>(k_cast4_fu_408_p1.read()) + sc_bigint<5>(tmp_6_reg_593.read()));
}

void feature_extractor_convolve::thread_y_fu_516_p2() {
    y_fu_516_p2 = (!tmp_s_reg_606.read().is_01() || !l_cast2_fu_500_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(tmp_s_reg_606.read()) + sc_biguint<5>(l_cast2_fu_500_p1.read()));
}

void feature_extractor_convolve::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond5_fu_228_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_299_p2.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_325_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_376_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_412_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_504_p2.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

