// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module obj_detector_fmax (
        ap_clk,
        ap_rst,
        x,
        y,
        ap_return
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_34 = 32'b110100;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv52_0 = 52'b0000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv52_8000000000000 = 52'b1000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input   ap_clk;
input   ap_rst;
input  [63:0] x;
input  [63:0] y;
output  [63:0] ap_return;

reg   [63:0] y_read_reg_250;
reg   [63:0] ap_reg_ppstg_y_read_reg_250_pp0_it1;
reg   [63:0] x_read_reg_258;
reg   [63:0] ap_reg_ppstg_x_read_reg_258_pp0_it1;
reg   [0:0] p_Result_6_reg_265;
reg   [0:0] ap_reg_ppstg_p_Result_6_reg_265_pp0_it1;
wire   [51:0] loc_V_1_fu_66_p1;
reg   [51:0] loc_V_1_reg_270;
reg   [51:0] ap_reg_ppstg_loc_V_1_reg_270_pp0_it1;
wire   [0:0] or_cond2_i_fu_124_p2;
reg   [0:0] or_cond2_i_reg_275;
reg   [0:0] ap_reg_ppstg_or_cond2_i_reg_275_pp0_it1;
wire   [0:0] or_cond3_i_fu_136_p2;
reg   [0:0] or_cond3_i_reg_282;
reg   [0:0] ap_reg_ppstg_or_cond3_i_reg_282_pp0_it1;
wire   [0:0] or_cond4_i_fu_148_p2;
reg   [0:0] or_cond4_i_reg_289;
reg   [0:0] ap_reg_ppstg_or_cond4_i_reg_289_pp0_it1;
wire   [0:0] tmp_s_fu_158_p2;
reg   [0:0] tmp_s_reg_297;
wire   [63:0] tmp_9_fu_40_p0;
wire   [63:0] tmp_9_fu_40_p1;
wire   [63:0] p_Val2_s_fu_44_p1;
wire   [63:0] p_Val2_1_fu_70_p1;
wire   [10:0] loc_V_fu_56_p4;
wire   [10:0] loc_V_2_fu_74_p4;
wire   [51:0] loc_V_3_fu_84_p1;
wire   [0:0] tmp_i_7_fu_94_p2;
wire   [0:0] tmp_1_i_fu_100_p2;
wire   [0:0] tmp_i_fu_88_p2;
wire   [0:0] tmp_2_i_fu_106_p2;
wire   [0:0] tmp1_fu_118_p2;
wire   [0:0] tmp_fu_112_p2;
wire   [0:0] tmp_3_i_fu_130_p2;
wire   [0:0] tmp_4_i_fu_142_p2;
wire   [0:0] tmp_8_fu_154_p2;
wire   [0:0] tmp_9_fu_40_p2;
wire   [51:0] x_fp_sig_V_fu_169_p2;
wire   [63:0] p_Result_s_fu_174_p4;
wire   [0:0] sel_tmp1_fu_187_p2;
wire   [0:0] sel_tmp2_fu_191_p2;
wire   [63:0] res_fu_164_p3;
wire   [63:0] res_1_fu_183_p1;
wire   [63:0] res_2_fu_196_p3;
wire   [0:0] sel_tmp7_demorgan_fu_210_p2;
wire   [0:0] sel_tmp7_fu_214_p2;
wire   [0:0] sel_tmp8_fu_220_p2;
wire   [63:0] res_3_fu_204_p3;
wire   [0:0] sel_tmp_fu_232_p2;
wire   [0:0] sel_tmp3_fu_237_p2;
wire   [63:0] res_4_fu_225_p3;
wire   [4:0] tmp_9_fu_40_opcode;


obj_detector_dcmp_64ns_64ns_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
obj_detector_dcmp_64ns_64ns_1_1_U28(
    .din0( tmp_9_fu_40_p0 ),
    .din1( tmp_9_fu_40_p1 ),
    .opcode( tmp_9_fu_40_opcode ),
    .dout( tmp_9_fu_40_p2 )
);



/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_true == ap_true)) begin
        ap_reg_ppstg_loc_V_1_reg_270_pp0_it1 <= loc_V_1_reg_270;
        ap_reg_ppstg_or_cond2_i_reg_275_pp0_it1 <= or_cond2_i_reg_275;
        ap_reg_ppstg_or_cond3_i_reg_282_pp0_it1 <= or_cond3_i_reg_282;
        ap_reg_ppstg_or_cond4_i_reg_289_pp0_it1 <= or_cond4_i_reg_289;
        ap_reg_ppstg_p_Result_6_reg_265_pp0_it1 <= p_Result_6_reg_265;
        ap_reg_ppstg_x_read_reg_258_pp0_it1 <= x_read_reg_258;
        ap_reg_ppstg_y_read_reg_250_pp0_it1 <= y_read_reg_250;
        loc_V_1_reg_270 <= loc_V_1_fu_66_p1;
        or_cond2_i_reg_275 <= or_cond2_i_fu_124_p2;
        or_cond3_i_reg_282 <= or_cond3_i_fu_136_p2;
        or_cond4_i_reg_289 <= or_cond4_i_fu_148_p2;
        p_Result_6_reg_265 <= p_Val2_s_fu_44_p1[ap_const_lv32_3F];
        x_read_reg_258 <= x;
        y_read_reg_250 <= y;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((or_cond2_i_reg_275 == ap_const_lv1_0)) begin
        tmp_s_reg_297 <= tmp_s_fu_158_p2;
    end
end
assign ap_return = ((sel_tmp3_fu_237_p2[0:0]===1'b1)? ap_reg_ppstg_x_read_reg_258_pp0_it1: res_4_fu_225_p3);
assign loc_V_1_fu_66_p1 = p_Val2_s_fu_44_p1[51:0];
assign loc_V_2_fu_74_p4 = {{p_Val2_1_fu_70_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign loc_V_3_fu_84_p1 = p_Val2_1_fu_70_p1[51:0];
assign loc_V_fu_56_p4 = {{p_Val2_s_fu_44_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
assign or_cond2_i_fu_124_p2 = (tmp1_fu_118_p2 & tmp_fu_112_p2);
assign or_cond3_i_fu_136_p2 = (tmp_3_i_fu_130_p2 | tmp_i_7_fu_94_p2);
assign or_cond4_i_fu_148_p2 = (tmp_4_i_fu_142_p2 | tmp_2_i_fu_106_p2);
assign p_Result_s_fu_174_p4 = {{{ap_reg_ppstg_p_Result_6_reg_265_pp0_it1}, {ap_const_lv11_7FF}}, {x_fp_sig_V_fu_169_p2}};
assign p_Val2_1_fu_70_p1 = y;
assign p_Val2_s_fu_44_p1 = x;
assign res_1_fu_183_p1 = p_Result_s_fu_174_p4;
assign res_2_fu_196_p3 = ((sel_tmp2_fu_191_p2[0:0]===1'b1)? res_fu_164_p3: res_1_fu_183_p1);
assign res_3_fu_204_p3 = ((ap_reg_ppstg_or_cond2_i_reg_275_pp0_it1[0:0]===1'b1)? ap_reg_ppstg_y_read_reg_250_pp0_it1: res_2_fu_196_p3);
assign res_4_fu_225_p3 = ((sel_tmp8_fu_220_p2[0:0]===1'b1)? ap_reg_ppstg_y_read_reg_250_pp0_it1: res_3_fu_204_p3);
assign res_fu_164_p3 = ((tmp_s_reg_297[0:0]===1'b1)? ap_reg_ppstg_x_read_reg_258_pp0_it1: ap_reg_ppstg_y_read_reg_250_pp0_it1);
assign sel_tmp1_fu_187_p2 = (ap_reg_ppstg_or_cond2_i_reg_275_pp0_it1 ^ ap_reg_ppstg_or_cond3_i_reg_282_pp0_it1);
assign sel_tmp2_fu_191_p2 = (sel_tmp1_fu_187_p2 & ap_reg_ppstg_or_cond4_i_reg_289_pp0_it1);
assign sel_tmp3_fu_237_p2 = (sel_tmp1_fu_187_p2 & sel_tmp_fu_232_p2);
assign sel_tmp7_demorgan_fu_210_p2 = (ap_reg_ppstg_or_cond2_i_reg_275_pp0_it1 | ap_reg_ppstg_or_cond3_i_reg_282_pp0_it1);
assign sel_tmp7_fu_214_p2 = (sel_tmp7_demorgan_fu_210_p2 ^ ap_const_lv1_1);
assign sel_tmp8_fu_220_p2 = (ap_reg_ppstg_or_cond4_i_reg_289_pp0_it1 & sel_tmp7_fu_214_p2);
assign sel_tmp_fu_232_p2 = (ap_reg_ppstg_or_cond4_i_reg_289_pp0_it1 ^ ap_const_lv1_1);
assign tmp1_fu_118_p2 = (tmp_i_fu_88_p2 & tmp_2_i_fu_106_p2);
assign tmp_1_i_fu_100_p2 = (loc_V_2_fu_74_p4 == ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_2_i_fu_106_p2 = (loc_V_3_fu_84_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign tmp_3_i_fu_130_p2 = (loc_V_fu_56_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign tmp_4_i_fu_142_p2 = (loc_V_2_fu_74_p4 != ap_const_lv11_7FF? 1'b1: 1'b0);
assign tmp_8_fu_154_p2 = (or_cond3_i_reg_282 & or_cond4_i_reg_289);
assign tmp_9_fu_40_opcode = ap_const_lv5_2;
assign tmp_9_fu_40_p0 = x_read_reg_258;
assign tmp_9_fu_40_p1 = y_read_reg_250;
assign tmp_fu_112_p2 = (tmp_i_7_fu_94_p2 & tmp_1_i_fu_100_p2);
assign tmp_i_7_fu_94_p2 = (loc_V_1_fu_66_p1 == ap_const_lv52_0? 1'b1: 1'b0);
assign tmp_i_fu_88_p2 = (loc_V_fu_56_p4 == ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_s_fu_158_p2 = (tmp_8_fu_154_p2 & tmp_9_fu_40_p2);
assign x_fp_sig_V_fu_169_p2 = (ap_reg_ppstg_loc_V_1_reg_270_pp0_it1 | ap_const_lv52_8000000000000);


endmodule //obj_detector_fmax

