// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void maxpool ( bool* begin, hls::stream< unsigned char >& input, hls::stream< unsigned char >& output,  bool* ok);
