#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("inp_Addr_A", 32, hls_out, 0, "bram", "mem_address", 1),
	Port_Property("inp_EN_A", 1, hls_out, 0, "bram", "mem_ce", 1),
	Port_Property("inp_WEN_A", 4, hls_out, 0, "bram", "mem_we", 1),
	Port_Property("inp_Din_A", 32, hls_out, 0, "bram", "mem_din", 1),
	Port_Property("inp_Dout_A", 32, hls_in, 0, "bram", "mem_dout", 1),
	Port_Property("inp_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("inp_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("out_r_Addr_A", 32, hls_out, 1, "bram", "mem_address", 1),
	Port_Property("out_r_EN_A", 1, hls_out, 1, "bram", "mem_ce", 1),
	Port_Property("out_r_WEN_A", 4, hls_out, 1, "bram", "mem_we", 1),
	Port_Property("out_r_Din_A", 32, hls_out, 1, "bram", "mem_din", 1),
	Port_Property("out_r_Dout_A", 32, hls_in, 1, "bram", "mem_dout", 1),
	Port_Property("out_r_Clk_A", 1, hls_out, 1, "bram", "mem_clk", 1),
	Port_Property("out_r_Rst_A", 1, hls_out, 1, "bram", "mem_rst", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "softmax";
