#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" ::: -10
#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 280 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 182
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 183
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 211
#pragma line 122 "/usr/include/features.h" 3 4 ::: 308
#pragma line 156 "/usr/include/features.h" 3 4 ::: 333
#pragma line 180 "/usr/include/features.h" 3 4 ::: 335
#pragma line 191 "/usr/include/features.h" 3 4 ::: 338
#pragma line 343 "/usr/include/features.h" 3 4 ::: 369
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 373
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 408
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 415
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 438
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 479
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 485
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 509
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 515
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 582
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 623
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 648
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 672
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 673
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 675
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 677
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 678
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 703
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 714
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 719
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 720
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 721
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 727
#pragma line 56 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 768
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 771
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 773
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 801
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 803
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 805
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 866
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 873
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 891
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 896
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 907
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 976
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 990
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 993
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 994
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1026
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1042
#pragma line 56 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1067
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1070
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1075
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1097
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1118
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1121
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1132
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1142
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1144
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1148
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1197
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1198
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1204
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1206
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1226
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1237
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1278
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1308
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1334
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1338
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1353
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1365
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1371
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1373
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1383
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1405
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1421
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1438
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1470
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1516
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1530
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1533
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1609
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1648
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1689
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1802
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1865
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1914
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1925
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1955
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1983
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2015
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2027
#pragma line 2 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 2030
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 2031
#pragma line 30 "/usr/include/math.h" 3 4 ::: 2053
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 2056
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 2082
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 2114
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 2115
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 2120
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 2145
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 2147
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 2172
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 2173
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 2192
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 2196
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 2220
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 2224
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 2249
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 2254
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2271
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2277
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 2284
#pragma line 83 "/usr/include/math.h" 3 4 ::: 2290
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2291
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2368
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2398
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2639
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 2642
#pragma line 93 "/usr/include/math.h" 3 4 ::: 2643
#pragma line 104 "/usr/include/math.h" 3 4 ::: 2646
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2647
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2724
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2754
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2995
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 2998
#pragma line 139 "/usr/include/math.h" 3 4 ::: 2999
#pragma line 151 "/usr/include/math.h" 3 4 ::: 3002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 3003
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3080
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3110
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3351
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 3354
#pragma line 167 "/usr/include/math.h" 3 4 ::: 3355
#pragma line 248 "/usr/include/math.h" 3 4 ::: 3422
#pragma line 268 "/usr/include/math.h" 3 4 ::: 3424
#pragma line 282 "/usr/include/math.h" 3 4 ::: 3426
#pragma line 304 "/usr/include/math.h" 3 4 ::: 3436
#pragma line 318 "/usr/include/math.h" 3 4 ::: 3438
#pragma line 346 "/usr/include/math.h" 3 4 ::: 3446
#pragma line 411 "/usr/include/math.h" 3 4 ::: 3500
#pragma line 428 "/usr/include/math.h" 3 4 ::: 3502
#pragma line 448 "/usr/include/math.h" 3 4 ::: 3506
#pragma line 470 "/usr/include/math.h" 3 4 ::: 3521
#pragma line 3 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 3577
