#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" ::: 0
#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 280 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 6 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 192
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 193
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 221
#pragma line 122 "/usr/include/features.h" 3 4 ::: 318
#pragma line 156 "/usr/include/features.h" 3 4 ::: 343
#pragma line 180 "/usr/include/features.h" 3 4 ::: 345
#pragma line 191 "/usr/include/features.h" 3 4 ::: 348
#pragma line 343 "/usr/include/features.h" 3 4 ::: 379
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 383
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 418
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 425
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 448
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 489
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 495
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 592
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 633
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 658
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 682
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 683
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 685
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 687
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 688
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 713
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 724
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 729
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 730
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 731
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 737
#pragma line 56 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 778
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 781
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 783
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 811
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 813
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 815
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 876
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 883
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 901
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 906
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 917
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 986
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1000
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1003
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1004
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1036
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1052
#pragma line 56 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1077
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1080
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1085
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1107
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1128
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1131
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1142
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1152
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1154
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1158
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1207
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1208
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1236
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1247
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1288
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1318
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1348
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1363
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1375
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1381
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1383
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1415
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1431
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1448
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1480
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1526
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1540
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1543
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1619
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1658
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1699
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1812
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1875
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1924
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1935
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1965
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1993
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2025
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2037
#pragma line 2 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 2040
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 2041
#pragma line 30 "/usr/include/math.h" 3 4 ::: 2063
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 2066
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 2092
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 2124
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 2125
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 2130
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 2155
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 2157
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 2182
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 2183
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 2202
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 2206
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 2230
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 2234
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 2259
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 2264
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2281
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 2287
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 2294
#pragma line 83 "/usr/include/math.h" 3 4 ::: 2300
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2301
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2378
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2408
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2649
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 2652
#pragma line 93 "/usr/include/math.h" 3 4 ::: 2653
#pragma line 104 "/usr/include/math.h" 3 4 ::: 2656
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 2657
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2734
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2764
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3005
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 3008
#pragma line 139 "/usr/include/math.h" 3 4 ::: 3009
#pragma line 151 "/usr/include/math.h" 3 4 ::: 3012
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 3013
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3090
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3120
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 3361
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 3364
#pragma line 167 "/usr/include/math.h" 3 4 ::: 3365
#pragma line 248 "/usr/include/math.h" 3 4 ::: 3432
#pragma line 268 "/usr/include/math.h" 3 4 ::: 3434
#pragma line 282 "/usr/include/math.h" 3 4 ::: 3436
#pragma line 304 "/usr/include/math.h" 3 4 ::: 3446
#pragma line 318 "/usr/include/math.h" 3 4 ::: 3448
#pragma line 346 "/usr/include/math.h" 3 4 ::: 3456
#pragma line 411 "/usr/include/math.h" 3 4 ::: 3510
#pragma line 428 "/usr/include/math.h" 3 4 ::: 3512
#pragma line 448 "/usr/include/math.h" 3 4 ::: 3516
#pragma line 470 "/usr/include/math.h" 3 4 ::: 3531
#pragma line 3 "cnn_layer_2/.settings/feature_descriminator.c" 2 ::: 3587
