#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("input_V_dout", 8, hls_in, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("input_V_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("input_V_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("output_0_V_din", 8, hls_out, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("output_0_V_full_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("output_0_V_write", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("output_1_V_din", 8, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("output_1_V_full_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("output_1_V_write", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("output_2_V_din", 8, hls_out, 3, "ap_fifo", "fifo_data", 1),
	Port_Property("output_2_V_full_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("output_2_V_write", 1, hls_out, 3, "ap_fifo", "fifo_update", 1),
	Port_Property("output_3_V_din", 8, hls_out, 4, "ap_fifo", "fifo_data", 1),
	Port_Property("output_3_V_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("output_3_V_write", 1, hls_out, 4, "ap_fifo", "fifo_update", 1),
	Port_Property("output_4_V_din", 8, hls_out, 5, "ap_fifo", "fifo_data", 1),
	Port_Property("output_4_V_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("output_4_V_write", 1, hls_out, 5, "ap_fifo", "fifo_update", 1),
	Port_Property("output_5_V_din", 8, hls_out, 6, "ap_fifo", "fifo_data", 1),
	Port_Property("output_5_V_full_n", 1, hls_in, 6, "ap_fifo", "fifo_status", 1),
	Port_Property("output_5_V_write", 1, hls_out, 6, "ap_fifo", "fifo_update", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "splitter";
