#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("input_V_TDATA", 8, hls_in, 0, "axis", "in_data", 1),
	Port_Property("output_0_V_TDATA", 8, hls_out, 1, "axis", "out_data", 1),
	Port_Property("output_1_V_TDATA", 8, hls_out, 2, "axis", "out_data", 1),
	Port_Property("output_2_V_TDATA", 8, hls_out, 3, "axis", "out_data", 1),
	Port_Property("output_3_V_TDATA", 8, hls_out, 4, "axis", "out_data", 1),
	Port_Property("output_4_V_TDATA", 8, hls_out, 5, "axis", "out_data", 1),
	Port_Property("output_5_V_TDATA", 8, hls_out, 6, "axis", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("input_V_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("input_V_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("output_0_V_TVALID", 1, hls_out, 1, "axis", "out_vld", 1),
	Port_Property("output_0_V_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("output_1_V_TVALID", 1, hls_out, 2, "axis", "out_vld", 1),
	Port_Property("output_1_V_TREADY", 1, hls_in, 2, "axis", "out_acc", 1),
	Port_Property("output_2_V_TVALID", 1, hls_out, 3, "axis", "out_vld", 1),
	Port_Property("output_2_V_TREADY", 1, hls_in, 3, "axis", "out_acc", 1),
	Port_Property("output_3_V_TVALID", 1, hls_out, 4, "axis", "out_vld", 1),
	Port_Property("output_3_V_TREADY", 1, hls_in, 4, "axis", "out_acc", 1),
	Port_Property("output_4_V_TVALID", 1, hls_out, 5, "axis", "out_vld", 1),
	Port_Property("output_4_V_TREADY", 1, hls_in, 5, "axis", "out_acc", 1),
	Port_Property("output_5_V_TVALID", 1, hls_out, 6, "axis", "out_vld", 1),
	Port_Property("output_5_V_TREADY", 1, hls_in, 6, "axis", "out_acc", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "splitter";
