-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.2
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity maxpool is
port (
    begin_r : IN STD_LOGIC;
    input_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    input_V_empty_n : IN STD_LOGIC;
    input_V_read : OUT STD_LOGIC;
    output_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_V_full_n : IN STD_LOGIC;
    output_V_write : OUT STD_LOGIC;
    ok : IN STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of maxpool is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "maxpool,hls_ip_2015_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.743000,HLS_SYN_LAT=579,HLS_SYN_TPT=580,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=457,HLS_SYN_LUT=484}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_true : BOOLEAN := true;

    signal maxpool_Loop_LOOP_proc_U0_ap_start : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_ap_done : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_ap_continue : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_ap_idle : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_ap_ready : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_output_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal maxpool_Loop_LOOP_proc_U0_output_V_full_n : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_output_V_write : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_input_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal maxpool_Loop_LOOP_proc_U0_input_V_empty_n : STD_LOGIC;
    signal maxpool_Loop_LOOP_proc_U0_input_V_read : STD_LOGIC;
    signal ap_sig_hs_continue : STD_LOGIC;
    signal ap_reg_procdone_maxpool_Loop_LOOP_proc_U0 : STD_LOGIC := '0';
    signal ap_sig_hs_done : STD_LOGIC;
    signal ap_CS : STD_LOGIC;
    signal ap_sig_top_allready : STD_LOGIC;

    component maxpool_Loop_LOOP_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_V_full_n : IN STD_LOGIC;
        output_V_write : OUT STD_LOGIC;
        input_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        input_V_empty_n : IN STD_LOGIC;
        input_V_read : OUT STD_LOGIC );
    end component;



begin
    maxpool_Loop_LOOP_proc_U0 : component maxpool_Loop_LOOP_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => maxpool_Loop_LOOP_proc_U0_ap_start,
        ap_done => maxpool_Loop_LOOP_proc_U0_ap_done,
        ap_continue => maxpool_Loop_LOOP_proc_U0_ap_continue,
        ap_idle => maxpool_Loop_LOOP_proc_U0_ap_idle,
        ap_ready => maxpool_Loop_LOOP_proc_U0_ap_ready,
        output_V_din => maxpool_Loop_LOOP_proc_U0_output_V_din,
        output_V_full_n => maxpool_Loop_LOOP_proc_U0_output_V_full_n,
        output_V_write => maxpool_Loop_LOOP_proc_U0_output_V_write,
        input_V_dout => maxpool_Loop_LOOP_proc_U0_input_V_dout,
        input_V_empty_n => maxpool_Loop_LOOP_proc_U0_input_V_empty_n,
        input_V_read => maxpool_Loop_LOOP_proc_U0_input_V_read);





    -- ap_reg_procdone_maxpool_Loop_LOOP_proc_U0 assign process. --
    ap_reg_procdone_maxpool_Loop_LOOP_proc_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_procdone_maxpool_Loop_LOOP_proc_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_maxpool_Loop_LOOP_proc_U0 <= ap_const_logic_0;
                elsif ((maxpool_Loop_LOOP_proc_U0_ap_done = ap_const_logic_1)) then 
                    ap_reg_procdone_maxpool_Loop_LOOP_proc_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_CS assign process. --
    ap_CS_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS <= ap_const_logic_0;
        end if;
    end process;
    ap_done <= ap_sig_hs_done;

    -- ap_idle assign process. --
    ap_idle_assign_proc : process(maxpool_Loop_LOOP_proc_U0_ap_idle)
    begin
        if ((maxpool_Loop_LOOP_proc_U0_ap_idle = ap_const_logic_1)) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_sig_top_allready;
    ap_sig_hs_continue <= ap_const_logic_1;

    -- ap_sig_hs_done assign process. --
    ap_sig_hs_done_assign_proc : process(maxpool_Loop_LOOP_proc_U0_ap_done)
    begin
        if ((maxpool_Loop_LOOP_proc_U0_ap_done = ap_const_logic_1)) then 
            ap_sig_hs_done <= ap_const_logic_1;
        else 
            ap_sig_hs_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_sig_top_allready <= maxpool_Loop_LOOP_proc_U0_ap_ready;
    input_V_read <= maxpool_Loop_LOOP_proc_U0_input_V_read;
    maxpool_Loop_LOOP_proc_U0_ap_continue <= ap_sig_hs_continue;
    maxpool_Loop_LOOP_proc_U0_ap_start <= ap_start;
    maxpool_Loop_LOOP_proc_U0_input_V_dout <= input_V_dout;
    maxpool_Loop_LOOP_proc_U0_input_V_empty_n <= input_V_empty_n;
    maxpool_Loop_LOOP_proc_U0_output_V_full_n <= output_V_full_n;
    output_V_din <= maxpool_Loop_LOOP_proc_U0_output_V_din;
    output_V_write <= maxpool_Loop_LOOP_proc_U0_output_V_write;
end behav;
