// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "obj_detector_softmax.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic obj_detector_softmax::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic obj_detector_softmax::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<99> obj_detector_softmax::ap_ST_st1_fsm_0 = "1";
const sc_lv<99> obj_detector_softmax::ap_ST_st2_fsm_1 = "10";
const sc_lv<99> obj_detector_softmax::ap_ST_st3_fsm_2 = "100";
const sc_lv<99> obj_detector_softmax::ap_ST_st4_fsm_3 = "1000";
const sc_lv<99> obj_detector_softmax::ap_ST_st5_fsm_4 = "10000";
const sc_lv<99> obj_detector_softmax::ap_ST_st6_fsm_5 = "100000";
const sc_lv<99> obj_detector_softmax::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st27_fsm_26 = "100000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st28_fsm_27 = "1000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st29_fsm_28 = "10000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st30_fsm_29 = "100000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st31_fsm_30 = "1000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st32_fsm_31 = "10000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st33_fsm_32 = "100000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st34_fsm_33 = "1000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st35_fsm_34 = "10000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st36_fsm_35 = "100000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st37_fsm_36 = "1000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st38_fsm_37 = "10000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st39_fsm_38 = "100000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st40_fsm_39 = "1000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st41_fsm_40 = "10000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st42_fsm_41 = "100000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st43_fsm_42 = "1000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st44_fsm_43 = "10000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st45_fsm_44 = "100000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st46_fsm_45 = "1000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st47_fsm_46 = "10000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st48_fsm_47 = "100000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st49_fsm_48 = "1000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st50_fsm_49 = "10000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st51_fsm_50 = "100000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st52_fsm_51 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st53_fsm_52 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st54_fsm_53 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st55_fsm_54 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st56_fsm_55 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st57_fsm_56 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st58_fsm_57 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st59_fsm_58 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st60_fsm_59 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st61_fsm_60 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st62_fsm_61 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st63_fsm_62 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st64_fsm_63 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st65_fsm_64 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st66_fsm_65 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st67_fsm_66 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st68_fsm_67 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st69_fsm_68 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st70_fsm_69 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st71_fsm_70 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st72_fsm_71 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st73_fsm_72 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st74_fsm_73 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st75_fsm_74 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st76_fsm_75 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st77_fsm_76 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st78_fsm_77 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st79_fsm_78 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st80_fsm_79 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st81_fsm_80 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st82_fsm_81 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st83_fsm_82 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st84_fsm_83 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st85_fsm_84 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st86_fsm_85 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st87_fsm_86 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st88_fsm_87 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st89_fsm_88 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st90_fsm_89 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st91_fsm_90 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st92_fsm_91 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st93_fsm_92 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st94_fsm_93 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st95_fsm_94 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st96_fsm_95 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st97_fsm_96 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st98_fsm_97 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<99> obj_detector_softmax::ap_ST_st99_fsm_98 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> obj_detector_softmax::ap_const_lv1_1 = "1";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_16 = "10110";
const sc_lv<1> obj_detector_softmax::ap_const_lv1_0 = "0";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_28 = "101000";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_41 = "1000001";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_2E = "101110";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_61 = "1100001";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_1 = "1";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_5 = "101";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_6 = "110";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_15 = "10101";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_2D = "101101";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_2F = "101111";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_60 = "1100000";
const sc_lv<2> obj_detector_softmax::ap_const_lv2_0 = "00";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_62 = "1100010";
const sc_lv<4> obj_detector_softmax::ap_const_lv4_0 = "0000";
const sc_lv<4> obj_detector_softmax::ap_const_lv4_F = "1111";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_2 = "10";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_29 = "101001";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_42 = "1000010";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_17 = "10111";
const sc_lv<32> obj_detector_softmax::ap_const_lv32_30 = "110000";
const sc_lv<2> obj_detector_softmax::ap_const_lv2_2 = "10";
const sc_lv<2> obj_detector_softmax::ap_const_lv2_1 = "1";
const sc_lv<64> obj_detector_softmax::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

obj_detector_softmax::obj_detector_softmax(sc_module_name name) : sc_module(name), mVcdFile(0) {
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52 = new obj_detector_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52");
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->clk(ap_clk);
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->reset(ap_rst);
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->din0(grp_fu_161_p0);
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->din1(grp_fu_161_p1);
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->ce(grp_fu_161_ce);
    obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52->dout(grp_fu_161_p2);
    obj_detector_fdiv_32ns_32ns_32_16_U53 = new obj_detector_fdiv_32ns_32ns_32_16<1,16,32,32,32>("obj_detector_fdiv_32ns_32ns_32_16_U53");
    obj_detector_fdiv_32ns_32ns_32_16_U53->clk(ap_clk);
    obj_detector_fdiv_32ns_32ns_32_16_U53->reset(ap_rst);
    obj_detector_fdiv_32ns_32ns_32_16_U53->din0(grp_fu_166_p0);
    obj_detector_fdiv_32ns_32ns_32_16_U53->din1(grp_fu_166_p1);
    obj_detector_fdiv_32ns_32ns_32_16_U53->ce(grp_fu_166_ce);
    obj_detector_fdiv_32ns_32ns_32_16_U53->dout(grp_fu_166_p2);
    obj_detector_fptrunc_64ns_32_1_U54 = new obj_detector_fptrunc_64ns_32_1<1,1,64,32>("obj_detector_fptrunc_64ns_32_1_U54");
    obj_detector_fptrunc_64ns_32_1_U54->din0(grp_fu_171_p0);
    obj_detector_fptrunc_64ns_32_1_U54->dout(grp_fu_171_p1);
    obj_detector_fpext_32ns_64_1_U55 = new obj_detector_fpext_32ns_64_1<1,1,32,64>("obj_detector_fpext_32ns_64_1_U55");
    obj_detector_fpext_32ns_64_1_U55->din0(grp_fu_174_p0);
    obj_detector_fpext_32ns_64_1_U55->dout(grp_fu_174_p1);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56 = new obj_detector_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>("obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56");
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->clk(ap_clk);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->reset(ap_rst);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->din0(grp_fu_179_p0);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->din1(grp_fu_179_p1);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->ce(grp_fu_179_ce);
    obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56->dout(grp_fu_179_p2);
    obj_detector_ddiv_64ns_64ns_64_31_U57 = new obj_detector_ddiv_64ns_64ns_64_31<1,31,64,64,64>("obj_detector_ddiv_64ns_64ns_64_31_U57");
    obj_detector_ddiv_64ns_64ns_64_31_U57->clk(ap_clk);
    obj_detector_ddiv_64ns_64ns_64_31_U57->reset(ap_rst);
    obj_detector_ddiv_64ns_64ns_64_31_U57->din0(grp_fu_183_p0);
    obj_detector_ddiv_64ns_64ns_64_31_U57->din1(grp_fu_183_p1);
    obj_detector_ddiv_64ns_64ns_64_31_U57->ce(grp_fu_183_ce);
    obj_detector_ddiv_64ns_64ns_64_31_U57->dout(grp_fu_183_p2);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58 = new obj_detector_dexp_64ns_64ns_64_18_full_dsp<1,18,64,64,64>("obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58");
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->clk(ap_clk);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->reset(ap_rst);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->din0(grp_fu_187_p0);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->din1(grp_fu_187_p1);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->ce(grp_fu_187_ce);
    obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58->dout(grp_fu_187_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st48_fsm_47 );
    sensitive << ( exitcond_fu_296_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st48_fsm_47 );
    sensitive << ( exitcond_fu_296_p2 );

    SC_METHOD(thread_ap_sig_bdd_117);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_139);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_163);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_173);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_180);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_197);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_211);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_220);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_236);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_249);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_258);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_271);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_299);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_324);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_333);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_341);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_348);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_117 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_bdd_236 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_139 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_bdd_341 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_197 );

    SC_METHOD(thread_ap_sig_cseq_ST_st41_fsm_40);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_ap_sig_cseq_ST_st42_fsm_41);
    sensitive << ( ap_sig_bdd_324 );

    SC_METHOD(thread_ap_sig_cseq_ST_st46_fsm_45);
    sensitive << ( ap_sig_bdd_249 );

    SC_METHOD(thread_ap_sig_cseq_ST_st47_fsm_46);
    sensitive << ( ap_sig_bdd_173 );

    SC_METHOD(thread_ap_sig_cseq_ST_st48_fsm_47);
    sensitive << ( ap_sig_bdd_258 );

    SC_METHOD(thread_ap_sig_cseq_ST_st49_fsm_48);
    sensitive << ( ap_sig_bdd_348 );

    SC_METHOD(thread_ap_sig_cseq_ST_st66_fsm_65);
    sensitive << ( ap_sig_bdd_163 );

    SC_METHOD(thread_ap_sig_cseq_ST_st67_fsm_66);
    sensitive << ( ap_sig_bdd_333 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_211 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_220 );

    SC_METHOD(thread_ap_sig_cseq_ST_st97_fsm_96);
    sensitive << ( ap_sig_bdd_271 );

    SC_METHOD(thread_ap_sig_cseq_ST_st98_fsm_97);
    sensitive << ( ap_sig_bdd_180 );

    SC_METHOD(thread_ap_sig_cseq_ST_st99_fsm_98);
    sensitive << ( ap_sig_bdd_299 );

    SC_METHOD(thread_exitcond1_fu_271_p2);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( i2_reg_138 );

    SC_METHOD(thread_exitcond2_fu_234_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( i1_reg_115 );

    SC_METHOD(thread_exitcond3_fu_211_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_68 );

    SC_METHOD(thread_exitcond_fu_296_p2);
    sensitive << ( ap_sig_cseq_ST_st48_fsm_47 );
    sensitive << ( i3_reg_149 );

    SC_METHOD(thread_grp_fu_161_ce);

    SC_METHOD(thread_grp_fu_161_p0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( sum_reg_79 );

    SC_METHOD(thread_grp_fu_161_p1);
    sensitive << ( inp_0_read );
    sensitive << ( inp_1_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_223_p1 );

    SC_METHOD(thread_grp_fu_166_ce);

    SC_METHOD(thread_grp_fu_166_p0);
    sensitive << ( inp_0_read );
    sensitive << ( inp_1_read );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_10_fu_246_p1 );

    SC_METHOD(thread_grp_fu_166_p1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( sum_reg_79 );

    SC_METHOD(thread_grp_fu_171_p0);
    sensitive << ( ap_sig_cseq_ST_st47_fsm_46 );
    sensitive << ( ap_sig_cseq_ST_st98_fsm_97 );
    sensitive << ( tmp_8_reg_393 );
    sensitive << ( tmp_4_reg_411 );

    SC_METHOD(thread_grp_fu_174_p0);
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( exitcond1_fu_271_p2 );
    sensitive << ( ap_sig_cseq_ST_st41_fsm_40 );
    sensitive << ( ap_sig_cseq_ST_st48_fsm_47 );
    sensitive << ( sum_1_phi_fu_130_p4 );
    sensitive << ( sum_1_reg_126 );
    sensitive << ( temp_load_phi_fu_287_p3 );
    sensitive << ( temp_load_1_phi_fu_312_p3 );

    SC_METHOD(thread_grp_fu_179_ce);

    SC_METHOD(thread_grp_fu_179_p0);
    sensitive << ( reg_192 );
    sensitive << ( ap_sig_cseq_ST_st42_fsm_41 );

    SC_METHOD(thread_grp_fu_179_p1);
    sensitive << ( reg_199 );
    sensitive << ( ap_sig_cseq_ST_st42_fsm_41 );

    SC_METHOD(thread_grp_fu_183_ce);

    SC_METHOD(thread_grp_fu_183_p0);
    sensitive << ( reg_199 );
    sensitive << ( ap_sig_cseq_ST_st67_fsm_66 );

    SC_METHOD(thread_grp_fu_183_p1);
    sensitive << ( reg_192 );
    sensitive << ( ap_sig_cseq_ST_st67_fsm_66 );

    SC_METHOD(thread_grp_fu_187_ce);

    SC_METHOD(thread_grp_fu_187_p0);

    SC_METHOD(thread_grp_fu_187_p1);
    sensitive << ( reg_192 );
    sensitive << ( tmp_2_reg_406 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st49_fsm_48 );

    SC_METHOD(thread_i_5_fu_217_p2);
    sensitive << ( i_reg_68 );

    SC_METHOD(thread_i_6_fu_240_p2);
    sensitive << ( i1_reg_115 );

    SC_METHOD(thread_i_7_fu_277_p2);
    sensitive << ( i2_reg_138 );

    SC_METHOD(thread_i_8_fu_302_p2);
    sensitive << ( i3_reg_149 );

    SC_METHOD(thread_out_r_Addr_A);
    sensitive << ( out_r_Addr_A_orig );

    SC_METHOD(thread_out_r_Addr_A_orig);
    sensitive << ( ap_sig_cseq_ST_st99_fsm_98 );
    sensitive << ( tmp_9_fu_321_p1 );

    SC_METHOD(thread_out_r_Din_A);
    sensitive << ( reg_205 );
    sensitive << ( ap_sig_cseq_ST_st99_fsm_98 );

    SC_METHOD(thread_out_r_EN_A);
    sensitive << ( ap_sig_cseq_ST_st99_fsm_98 );

    SC_METHOD(thread_out_r_WEN_A);
    sensitive << ( ap_sig_cseq_ST_st99_fsm_98 );

    SC_METHOD(thread_sum_1_phi_fu_130_p4);
    sensitive << ( sum_1_reg_126 );

    SC_METHOD(thread_temp_1_1_fu_257_p3);
    sensitive << ( tmp_10_reg_364 );
    sensitive << ( temp_1_s_reg_91 );
    sensitive << ( grp_fu_166_p2 );

    SC_METHOD(thread_temp_1_2_fu_264_p3);
    sensitive << ( tmp_10_reg_364 );
    sensitive << ( temp_0_s_reg_103 );
    sensitive << ( grp_fu_166_p2 );

    SC_METHOD(thread_temp_load_1_phi_fu_312_p3);
    sensitive << ( temp_1_s_reg_91 );
    sensitive << ( temp_0_s_reg_103 );
    sensitive << ( tmp_12_fu_308_p1 );

    SC_METHOD(thread_temp_load_phi_fu_287_p3);
    sensitive << ( temp_1_s_reg_91 );
    sensitive << ( temp_0_s_reg_103 );
    sensitive << ( tmp_11_fu_283_p1 );

    SC_METHOD(thread_tmp_10_fu_246_p1);
    sensitive << ( i1_reg_115 );

    SC_METHOD(thread_tmp_11_fu_283_p1);
    sensitive << ( i2_reg_138 );

    SC_METHOD(thread_tmp_12_fu_308_p1);
    sensitive << ( i3_reg_149 );

    SC_METHOD(thread_tmp_9_fu_321_p1);
    sensitive << ( i3_reg_149 );

    SC_METHOD(thread_tmp_fu_223_p1);
    sensitive << ( i_reg_68 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_271_p2 );
    sensitive << ( exitcond3_fu_211_p2 );
    sensitive << ( exitcond2_fu_234_p2 );
    sensitive << ( exitcond_fu_296_p2 );

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "obj_detector_softmax_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inp_0_read, "(port)inp_0_read");
    sc_trace(mVcdFile, inp_1_read, "(port)inp_1_read");
    sc_trace(mVcdFile, out_r_Addr_A, "(port)out_r_Addr_A");
    sc_trace(mVcdFile, out_r_EN_A, "(port)out_r_EN_A");
    sc_trace(mVcdFile, out_r_WEN_A, "(port)out_r_WEN_A");
    sc_trace(mVcdFile, out_r_Din_A, "(port)out_r_Din_A");
    sc_trace(mVcdFile, out_r_Dout_A, "(port)out_r_Dout_A");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_117, "ap_sig_bdd_117");
    sc_trace(mVcdFile, grp_fu_174_p1, "grp_fu_174_p1");
    sc_trace(mVcdFile, reg_192, "reg_192");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_139, "ap_sig_bdd_139");
    sc_trace(mVcdFile, exitcond1_fu_271_p2, "exitcond1_fu_271_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st41_fsm_40, "ap_sig_cseq_ST_st41_fsm_40");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, grp_fu_187_p2, "grp_fu_187_p2");
    sc_trace(mVcdFile, reg_199, "reg_199");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st66_fsm_65, "ap_sig_cseq_ST_st66_fsm_65");
    sc_trace(mVcdFile, ap_sig_bdd_163, "ap_sig_bdd_163");
    sc_trace(mVcdFile, grp_fu_171_p1, "grp_fu_171_p1");
    sc_trace(mVcdFile, reg_205, "reg_205");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st47_fsm_46, "ap_sig_cseq_ST_st47_fsm_46");
    sc_trace(mVcdFile, ap_sig_bdd_173, "ap_sig_bdd_173");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st98_fsm_97, "ap_sig_cseq_ST_st98_fsm_97");
    sc_trace(mVcdFile, ap_sig_bdd_180, "ap_sig_bdd_180");
    sc_trace(mVcdFile, i_5_fu_217_p2, "i_5_fu_217_p2");
    sc_trace(mVcdFile, i_5_reg_341, "i_5_reg_341");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_197, "ap_sig_bdd_197");
    sc_trace(mVcdFile, exitcond3_fu_211_p2, "exitcond3_fu_211_p2");
    sc_trace(mVcdFile, grp_fu_161_p2, "grp_fu_161_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_211, "ap_sig_bdd_211");
    sc_trace(mVcdFile, i_6_fu_240_p2, "i_6_fu_240_p2");
    sc_trace(mVcdFile, i_6_reg_359, "i_6_reg_359");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_220, "ap_sig_bdd_220");
    sc_trace(mVcdFile, tmp_10_fu_246_p1, "tmp_10_fu_246_p1");
    sc_trace(mVcdFile, tmp_10_reg_364, "tmp_10_reg_364");
    sc_trace(mVcdFile, exitcond2_fu_234_p2, "exitcond2_fu_234_p2");
    sc_trace(mVcdFile, temp_1_1_fu_257_p3, "temp_1_1_fu_257_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_bdd_236, "ap_sig_bdd_236");
    sc_trace(mVcdFile, temp_1_2_fu_264_p3, "temp_1_2_fu_264_p3");
    sc_trace(mVcdFile, i_7_fu_277_p2, "i_7_fu_277_p2");
    sc_trace(mVcdFile, i_7_reg_388, "i_7_reg_388");
    sc_trace(mVcdFile, grp_fu_179_p2, "grp_fu_179_p2");
    sc_trace(mVcdFile, tmp_8_reg_393, "tmp_8_reg_393");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st46_fsm_45, "ap_sig_cseq_ST_st46_fsm_45");
    sc_trace(mVcdFile, ap_sig_bdd_249, "ap_sig_bdd_249");
    sc_trace(mVcdFile, i_8_fu_302_p2, "i_8_fu_302_p2");
    sc_trace(mVcdFile, i_8_reg_401, "i_8_reg_401");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st48_fsm_47, "ap_sig_cseq_ST_st48_fsm_47");
    sc_trace(mVcdFile, ap_sig_bdd_258, "ap_sig_bdd_258");
    sc_trace(mVcdFile, tmp_2_reg_406, "tmp_2_reg_406");
    sc_trace(mVcdFile, exitcond_fu_296_p2, "exitcond_fu_296_p2");
    sc_trace(mVcdFile, grp_fu_183_p2, "grp_fu_183_p2");
    sc_trace(mVcdFile, tmp_4_reg_411, "tmp_4_reg_411");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st97_fsm_96, "ap_sig_cseq_ST_st97_fsm_96");
    sc_trace(mVcdFile, ap_sig_bdd_271, "ap_sig_bdd_271");
    sc_trace(mVcdFile, i_reg_68, "i_reg_68");
    sc_trace(mVcdFile, sum_reg_79, "sum_reg_79");
    sc_trace(mVcdFile, temp_1_s_reg_91, "temp_1_s_reg_91");
    sc_trace(mVcdFile, temp_0_s_reg_103, "temp_0_s_reg_103");
    sc_trace(mVcdFile, i1_reg_115, "i1_reg_115");
    sc_trace(mVcdFile, sum_1_phi_fu_130_p4, "sum_1_phi_fu_130_p4");
    sc_trace(mVcdFile, sum_1_reg_126, "sum_1_reg_126");
    sc_trace(mVcdFile, i2_reg_138, "i2_reg_138");
    sc_trace(mVcdFile, i3_reg_149, "i3_reg_149");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st99_fsm_98, "ap_sig_cseq_ST_st99_fsm_98");
    sc_trace(mVcdFile, ap_sig_bdd_299, "ap_sig_bdd_299");
    sc_trace(mVcdFile, tmp_9_fu_321_p1, "tmp_9_fu_321_p1");
    sc_trace(mVcdFile, out_r_Addr_A_orig, "out_r_Addr_A_orig");
    sc_trace(mVcdFile, grp_fu_161_p0, "grp_fu_161_p0");
    sc_trace(mVcdFile, grp_fu_161_p1, "grp_fu_161_p1");
    sc_trace(mVcdFile, grp_fu_166_p0, "grp_fu_166_p0");
    sc_trace(mVcdFile, grp_fu_166_p1, "grp_fu_166_p1");
    sc_trace(mVcdFile, grp_fu_171_p0, "grp_fu_171_p0");
    sc_trace(mVcdFile, grp_fu_174_p0, "grp_fu_174_p0");
    sc_trace(mVcdFile, temp_load_phi_fu_287_p3, "temp_load_phi_fu_287_p3");
    sc_trace(mVcdFile, temp_load_1_phi_fu_312_p3, "temp_load_1_phi_fu_312_p3");
    sc_trace(mVcdFile, grp_fu_179_p0, "grp_fu_179_p0");
    sc_trace(mVcdFile, grp_fu_179_p1, "grp_fu_179_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st42_fsm_41, "ap_sig_cseq_ST_st42_fsm_41");
    sc_trace(mVcdFile, ap_sig_bdd_324, "ap_sig_bdd_324");
    sc_trace(mVcdFile, grp_fu_183_p0, "grp_fu_183_p0");
    sc_trace(mVcdFile, grp_fu_183_p1, "grp_fu_183_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st67_fsm_66, "ap_sig_cseq_ST_st67_fsm_66");
    sc_trace(mVcdFile, ap_sig_bdd_333, "ap_sig_bdd_333");
    sc_trace(mVcdFile, grp_fu_187_p1, "grp_fu_187_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_bdd_341, "ap_sig_bdd_341");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st49_fsm_48, "ap_sig_cseq_ST_st49_fsm_48");
    sc_trace(mVcdFile, ap_sig_bdd_348, "ap_sig_bdd_348");
    sc_trace(mVcdFile, tmp_fu_223_p1, "tmp_fu_223_p1");
    sc_trace(mVcdFile, grp_fu_166_p2, "grp_fu_166_p2");
    sc_trace(mVcdFile, tmp_11_fu_283_p1, "tmp_11_fu_283_p1");
    sc_trace(mVcdFile, tmp_12_fu_308_p1, "tmp_12_fu_308_p1");
    sc_trace(mVcdFile, grp_fu_161_ce, "grp_fu_161_ce");
    sc_trace(mVcdFile, grp_fu_166_ce, "grp_fu_166_ce");
    sc_trace(mVcdFile, grp_fu_179_ce, "grp_fu_179_ce");
    sc_trace(mVcdFile, grp_fu_183_ce, "grp_fu_183_ce");
    sc_trace(mVcdFile, grp_fu_187_p0, "grp_fu_187_p0");
    sc_trace(mVcdFile, grp_fu_187_ce, "grp_fu_187_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

obj_detector_softmax::~obj_detector_softmax() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete obj_detector_fadd_32ns_32ns_32_5_full_dsp_U52;
    delete obj_detector_fdiv_32ns_32ns_32_16_U53;
    delete obj_detector_fptrunc_64ns_32_1_U54;
    delete obj_detector_fpext_32ns_64_1_U55;
    delete obj_detector_dadd_64ns_64ns_64_5_full_dsp_U56;
    delete obj_detector_ddiv_64ns_64ns_64_31_U57;
    delete obj_detector_dexp_64ns_64ns_64_18_full_dsp_U58;
}

void obj_detector_softmax::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_211_p2.read()))) {
        i1_reg_115 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        i1_reg_115 = i_6_reg_359.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_234_p2.read()))) {
        i2_reg_138 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st47_fsm_46.read())) {
        i2_reg_138 = i_7_reg_388.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0))) {
        i3_reg_149 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st99_fsm_98.read())) {
        i3_reg_149 = i_8_reg_401.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        i_reg_68 = i_5_reg_341.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_68 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_234_p2.read()))) {
        sum_1_reg_126 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st47_fsm_46.read())) {
        sum_1_reg_126 = grp_fu_171_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        sum_reg_79 = grp_fu_161_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        sum_reg_79 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_5_reg_341 = i_5_fu_217_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        i_6_reg_359 = i_6_fu_240_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        i_7_reg_388 = i_7_fu_277_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read())) {
        i_8_reg_401 = i_8_fu_302_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
  esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
  !esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st41_fsm_40.read()))) {
        reg_192 = grp_fu_174_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st41_fsm_40.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st66_fsm_65.read()))) {
        reg_199 = grp_fu_187_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st47_fsm_46.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st98_fsm_97.read()))) {
        reg_205 = grp_fu_171_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        temp_0_s_reg_103 = temp_1_2_fu_264_p3.read();
        temp_1_s_reg_91 = temp_1_1_fu_257_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_234_p2.read()))) {
        tmp_10_reg_364 = tmp_10_fu_246_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_296_p2.read()))) {
        tmp_2_reg_406 = grp_fu_174_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st97_fsm_96.read())) {
        tmp_4_reg_411 = grp_fu_183_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st46_fsm_45.read())) {
        tmp_8_reg_393 = grp_fu_179_p2.read();
    }
}

void obj_detector_softmax::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_296_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_296_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_bdd_117() {
    ap_sig_bdd_117 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void obj_detector_softmax::thread_ap_sig_bdd_139() {
    ap_sig_bdd_139 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void obj_detector_softmax::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(40, 40));
}

void obj_detector_softmax::thread_ap_sig_bdd_163() {
    ap_sig_bdd_163 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(65, 65));
}

void obj_detector_softmax::thread_ap_sig_bdd_173() {
    ap_sig_bdd_173 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(46, 46));
}

void obj_detector_softmax::thread_ap_sig_bdd_180() {
    ap_sig_bdd_180 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(97, 97));
}

void obj_detector_softmax::thread_ap_sig_bdd_197() {
    ap_sig_bdd_197 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void obj_detector_softmax::thread_ap_sig_bdd_211() {
    ap_sig_bdd_211 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void obj_detector_softmax::thread_ap_sig_bdd_220() {
    ap_sig_bdd_220 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void obj_detector_softmax::thread_ap_sig_bdd_236() {
    ap_sig_bdd_236 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void obj_detector_softmax::thread_ap_sig_bdd_249() {
    ap_sig_bdd_249 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(45, 45));
}

void obj_detector_softmax::thread_ap_sig_bdd_258() {
    ap_sig_bdd_258 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(47, 47));
}

void obj_detector_softmax::thread_ap_sig_bdd_271() {
    ap_sig_bdd_271 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(96, 96));
}

void obj_detector_softmax::thread_ap_sig_bdd_299() {
    ap_sig_bdd_299 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(98, 98));
}

void obj_detector_softmax::thread_ap_sig_bdd_324() {
    ap_sig_bdd_324 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(41, 41));
}

void obj_detector_softmax::thread_ap_sig_bdd_333() {
    ap_sig_bdd_333 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(66, 66));
}

void obj_detector_softmax::thread_ap_sig_bdd_341() {
    ap_sig_bdd_341 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void obj_detector_softmax::thread_ap_sig_bdd_348() {
    ap_sig_bdd_348 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(48, 48));
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_117.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_bdd_236.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_139.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_bdd_341.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_197.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st41_fsm_40() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st42_fsm_41() {
    if (ap_sig_bdd_324.read()) {
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st46_fsm_45() {
    if (ap_sig_bdd_249.read()) {
        ap_sig_cseq_ST_st46_fsm_45 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st46_fsm_45 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st47_fsm_46() {
    if (ap_sig_bdd_173.read()) {
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st48_fsm_47() {
    if (ap_sig_bdd_258.read()) {
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st49_fsm_48() {
    if (ap_sig_bdd_348.read()) {
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st66_fsm_65() {
    if (ap_sig_bdd_163.read()) {
        ap_sig_cseq_ST_st66_fsm_65 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st66_fsm_65 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st67_fsm_66() {
    if (ap_sig_bdd_333.read()) {
        ap_sig_cseq_ST_st67_fsm_66 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st67_fsm_66 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_211.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_220.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st97_fsm_96() {
    if (ap_sig_bdd_271.read()) {
        ap_sig_cseq_ST_st97_fsm_96 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st97_fsm_96 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st98_fsm_97() {
    if (ap_sig_bdd_180.read()) {
        ap_sig_cseq_ST_st98_fsm_97 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st98_fsm_97 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_ap_sig_cseq_ST_st99_fsm_98() {
    if (ap_sig_bdd_299.read()) {
        ap_sig_cseq_ST_st99_fsm_98 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st99_fsm_98 = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_exitcond1_fu_271_p2() {
    exitcond1_fu_271_p2 = (!i2_reg_138.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_138.read() == ap_const_lv2_2);
}

void obj_detector_softmax::thread_exitcond2_fu_234_p2() {
    exitcond2_fu_234_p2 = (!i1_reg_115.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_115.read() == ap_const_lv2_2);
}

void obj_detector_softmax::thread_exitcond3_fu_211_p2() {
    exitcond3_fu_211_p2 = (!i_reg_68.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_68.read() == ap_const_lv2_2);
}

void obj_detector_softmax::thread_exitcond_fu_296_p2() {
    exitcond_fu_296_p2 = (!i3_reg_149.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i3_reg_149.read() == ap_const_lv2_2);
}

void obj_detector_softmax::thread_grp_fu_161_ce() {
    grp_fu_161_ce = ap_const_logic_1;
}

void obj_detector_softmax::thread_grp_fu_161_p0() {
    grp_fu_161_p0 = sum_reg_79.read();
}

void obj_detector_softmax::thread_grp_fu_161_p1() {
    grp_fu_161_p1 = (!tmp_fu_223_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_fu_223_p1.read()[0].to_bool())? inp_1_read.read(): inp_0_read.read());
}

void obj_detector_softmax::thread_grp_fu_166_ce() {
    grp_fu_166_ce = ap_const_logic_1;
}

void obj_detector_softmax::thread_grp_fu_166_p0() {
    grp_fu_166_p0 = (!tmp_10_fu_246_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_10_fu_246_p1.read()[0].to_bool())? inp_1_read.read(): inp_0_read.read());
}

void obj_detector_softmax::thread_grp_fu_166_p1() {
    grp_fu_166_p1 = sum_reg_79.read();
}

void obj_detector_softmax::thread_grp_fu_171_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st98_fsm_97.read())) {
        grp_fu_171_p0 = tmp_4_reg_411.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st47_fsm_46.read())) {
        grp_fu_171_p0 = tmp_8_reg_393.read();
    } else {
        grp_fu_171_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void obj_detector_softmax::thread_grp_fu_174_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read())) {
        grp_fu_174_p0 = temp_load_1_phi_fu_312_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st41_fsm_40.read())) {
        grp_fu_174_p0 = sum_1_reg_126.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0))) {
        grp_fu_174_p0 = sum_1_phi_fu_130_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0))) {
        grp_fu_174_p0 = temp_load_phi_fu_287_p3.read();
    } else {
        grp_fu_174_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void obj_detector_softmax::thread_grp_fu_179_ce() {
    grp_fu_179_ce = ap_const_logic_1;
}

void obj_detector_softmax::thread_grp_fu_179_p0() {
    grp_fu_179_p0 = reg_192.read();
}

void obj_detector_softmax::thread_grp_fu_179_p1() {
    grp_fu_179_p1 = reg_199.read();
}

void obj_detector_softmax::thread_grp_fu_183_ce() {
    grp_fu_183_ce = ap_const_logic_1;
}

void obj_detector_softmax::thread_grp_fu_183_p0() {
    grp_fu_183_p0 = reg_199.read();
}

void obj_detector_softmax::thread_grp_fu_183_p1() {
    grp_fu_183_p1 = reg_192.read();
}

void obj_detector_softmax::thread_grp_fu_187_ce() {
    grp_fu_187_ce = ap_const_logic_1;
}

void obj_detector_softmax::thread_grp_fu_187_p0() {
    grp_fu_187_p0 = ap_const_lv64_0;
}

void obj_detector_softmax::thread_grp_fu_187_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st49_fsm_48.read())) {
        grp_fu_187_p1 = tmp_2_reg_406.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_187_p1 = reg_192.read();
    } else {
        grp_fu_187_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void obj_detector_softmax::thread_i_5_fu_217_p2() {
    i_5_fu_217_p2 = (!i_reg_68.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_reg_68.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void obj_detector_softmax::thread_i_6_fu_240_p2() {
    i_6_fu_240_p2 = (!i1_reg_115.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_115.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void obj_detector_softmax::thread_i_7_fu_277_p2() {
    i_7_fu_277_p2 = (!i2_reg_138.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_reg_138.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void obj_detector_softmax::thread_i_8_fu_302_p2() {
    i_8_fu_302_p2 = (!i3_reg_149.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i3_reg_149.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void obj_detector_softmax::thread_out_r_Addr_A() {
    out_r_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): out_r_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void obj_detector_softmax::thread_out_r_Addr_A_orig() {
    out_r_Addr_A_orig =  (sc_lv<32>) (tmp_9_fu_321_p1.read());
}

void obj_detector_softmax::thread_out_r_Din_A() {
    out_r_Din_A = reg_205.read();
}

void obj_detector_softmax::thread_out_r_EN_A() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st99_fsm_98.read())) {
        out_r_EN_A = ap_const_logic_1;
    } else {
        out_r_EN_A = ap_const_logic_0;
    }
}

void obj_detector_softmax::thread_out_r_WEN_A() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st99_fsm_98.read()))) {
        out_r_WEN_A = ap_const_lv4_F;
    } else {
        out_r_WEN_A = ap_const_lv4_0;
    }
}

void obj_detector_softmax::thread_sum_1_phi_fu_130_p4() {
    sum_1_phi_fu_130_p4 = sum_1_reg_126.read();
}

void obj_detector_softmax::thread_temp_1_1_fu_257_p3() {
    temp_1_1_fu_257_p3 = (!tmp_10_reg_364.read()[0].is_01())? sc_lv<32>(): ((tmp_10_reg_364.read()[0].to_bool())? grp_fu_166_p2.read(): temp_1_s_reg_91.read());
}

void obj_detector_softmax::thread_temp_1_2_fu_264_p3() {
    temp_1_2_fu_264_p3 = (!tmp_10_reg_364.read()[0].is_01())? sc_lv<32>(): ((tmp_10_reg_364.read()[0].to_bool())? temp_0_s_reg_103.read(): grp_fu_166_p2.read());
}

void obj_detector_softmax::thread_temp_load_1_phi_fu_312_p3() {
    temp_load_1_phi_fu_312_p3 = (!tmp_12_fu_308_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_12_fu_308_p1.read()[0].to_bool())? temp_1_s_reg_91.read(): temp_0_s_reg_103.read());
}

void obj_detector_softmax::thread_temp_load_phi_fu_287_p3() {
    temp_load_phi_fu_287_p3 = (!tmp_11_fu_283_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_11_fu_283_p1.read()[0].to_bool())? temp_1_s_reg_91.read(): temp_0_s_reg_103.read());
}

void obj_detector_softmax::thread_tmp_10_fu_246_p1() {
    tmp_10_fu_246_p1 = i1_reg_115.read().range(1-1, 0);
}

void obj_detector_softmax::thread_tmp_11_fu_283_p1() {
    tmp_11_fu_283_p1 = i2_reg_138.read().range(1-1, 0);
}

void obj_detector_softmax::thread_tmp_12_fu_308_p1() {
    tmp_12_fu_308_p1 = i3_reg_149.read().range(1-1, 0);
}

void obj_detector_softmax::thread_tmp_9_fu_321_p1() {
    tmp_9_fu_321_p1 = esl_zext<64,2>(i3_reg_149.read());
}

void obj_detector_softmax::thread_tmp_fu_223_p1() {
    tmp_fu_223_p1 = i_reg_68.read().range(1-1, 0);
}

void obj_detector_softmax::thread_ap_NS_fsm() {
    if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st1_fsm_0))
    {
        if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
            ap_NS_fsm = ap_ST_st2_fsm_1;
        } else {
            ap_NS_fsm = ap_ST_st1_fsm_0;
        }
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st2_fsm_1))
    {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_211_p2.read())) {
            ap_NS_fsm = ap_ST_st7_fsm_6;
        } else {
            ap_NS_fsm = ap_ST_st3_fsm_2;
        }
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st3_fsm_2))
    {
        ap_NS_fsm = ap_ST_st4_fsm_3;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st4_fsm_3))
    {
        ap_NS_fsm = ap_ST_st5_fsm_4;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st5_fsm_4))
    {
        ap_NS_fsm = ap_ST_st6_fsm_5;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st6_fsm_5))
    {
        ap_NS_fsm = ap_ST_st2_fsm_1;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st7_fsm_6))
    {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_234_p2.read())) {
            ap_NS_fsm = ap_ST_st23_fsm_22;
        } else {
            ap_NS_fsm = ap_ST_st8_fsm_7;
        }
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st8_fsm_7))
    {
        ap_NS_fsm = ap_ST_st9_fsm_8;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st9_fsm_8))
    {
        ap_NS_fsm = ap_ST_st10_fsm_9;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st10_fsm_9))
    {
        ap_NS_fsm = ap_ST_st11_fsm_10;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st11_fsm_10))
    {
        ap_NS_fsm = ap_ST_st12_fsm_11;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st12_fsm_11))
    {
        ap_NS_fsm = ap_ST_st13_fsm_12;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st13_fsm_12))
    {
        ap_NS_fsm = ap_ST_st14_fsm_13;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st14_fsm_13))
    {
        ap_NS_fsm = ap_ST_st15_fsm_14;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st15_fsm_14))
    {
        ap_NS_fsm = ap_ST_st16_fsm_15;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st16_fsm_15))
    {
        ap_NS_fsm = ap_ST_st17_fsm_16;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st17_fsm_16))
    {
        ap_NS_fsm = ap_ST_st18_fsm_17;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st18_fsm_17))
    {
        ap_NS_fsm = ap_ST_st19_fsm_18;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st19_fsm_18))
    {
        ap_NS_fsm = ap_ST_st20_fsm_19;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st20_fsm_19))
    {
        ap_NS_fsm = ap_ST_st21_fsm_20;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st21_fsm_20))
    {
        ap_NS_fsm = ap_ST_st22_fsm_21;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st22_fsm_21))
    {
        ap_NS_fsm = ap_ST_st7_fsm_6;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st23_fsm_22))
    {
        if (!esl_seteq<1,1,1>(exitcond1_fu_271_p2.read(), ap_const_lv1_0)) {
            ap_NS_fsm = ap_ST_st48_fsm_47;
        } else {
            ap_NS_fsm = ap_ST_st24_fsm_23;
        }
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st24_fsm_23))
    {
        ap_NS_fsm = ap_ST_st25_fsm_24;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st25_fsm_24))
    {
        ap_NS_fsm = ap_ST_st26_fsm_25;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st26_fsm_25))
    {
        ap_NS_fsm = ap_ST_st27_fsm_26;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st27_fsm_26))
    {
        ap_NS_fsm = ap_ST_st28_fsm_27;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st28_fsm_27))
    {
        ap_NS_fsm = ap_ST_st29_fsm_28;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st29_fsm_28))
    {
        ap_NS_fsm = ap_ST_st30_fsm_29;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st30_fsm_29))
    {
        ap_NS_fsm = ap_ST_st31_fsm_30;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st31_fsm_30))
    {
        ap_NS_fsm = ap_ST_st32_fsm_31;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st32_fsm_31))
    {
        ap_NS_fsm = ap_ST_st33_fsm_32;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st33_fsm_32))
    {
        ap_NS_fsm = ap_ST_st34_fsm_33;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st34_fsm_33))
    {
        ap_NS_fsm = ap_ST_st35_fsm_34;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st35_fsm_34))
    {
        ap_NS_fsm = ap_ST_st36_fsm_35;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st36_fsm_35))
    {
        ap_NS_fsm = ap_ST_st37_fsm_36;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st37_fsm_36))
    {
        ap_NS_fsm = ap_ST_st38_fsm_37;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st38_fsm_37))
    {
        ap_NS_fsm = ap_ST_st39_fsm_38;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st39_fsm_38))
    {
        ap_NS_fsm = ap_ST_st40_fsm_39;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st40_fsm_39))
    {
        ap_NS_fsm = ap_ST_st41_fsm_40;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st41_fsm_40))
    {
        ap_NS_fsm = ap_ST_st42_fsm_41;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st42_fsm_41))
    {
        ap_NS_fsm = ap_ST_st43_fsm_42;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st43_fsm_42))
    {
        ap_NS_fsm = ap_ST_st44_fsm_43;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st44_fsm_43))
    {
        ap_NS_fsm = ap_ST_st45_fsm_44;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st45_fsm_44))
    {
        ap_NS_fsm = ap_ST_st46_fsm_45;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st46_fsm_45))
    {
        ap_NS_fsm = ap_ST_st47_fsm_46;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st47_fsm_46))
    {
        ap_NS_fsm = ap_ST_st23_fsm_22;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st48_fsm_47))
    {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_296_p2.read())) {
            ap_NS_fsm = ap_ST_st1_fsm_0;
        } else {
            ap_NS_fsm = ap_ST_st49_fsm_48;
        }
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st49_fsm_48))
    {
        ap_NS_fsm = ap_ST_st50_fsm_49;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st50_fsm_49))
    {
        ap_NS_fsm = ap_ST_st51_fsm_50;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st51_fsm_50))
    {
        ap_NS_fsm = ap_ST_st52_fsm_51;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st52_fsm_51))
    {
        ap_NS_fsm = ap_ST_st53_fsm_52;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st53_fsm_52))
    {
        ap_NS_fsm = ap_ST_st54_fsm_53;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st54_fsm_53))
    {
        ap_NS_fsm = ap_ST_st55_fsm_54;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st55_fsm_54))
    {
        ap_NS_fsm = ap_ST_st56_fsm_55;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st56_fsm_55))
    {
        ap_NS_fsm = ap_ST_st57_fsm_56;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st57_fsm_56))
    {
        ap_NS_fsm = ap_ST_st58_fsm_57;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st58_fsm_57))
    {
        ap_NS_fsm = ap_ST_st59_fsm_58;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st59_fsm_58))
    {
        ap_NS_fsm = ap_ST_st60_fsm_59;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st60_fsm_59))
    {
        ap_NS_fsm = ap_ST_st61_fsm_60;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st61_fsm_60))
    {
        ap_NS_fsm = ap_ST_st62_fsm_61;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st62_fsm_61))
    {
        ap_NS_fsm = ap_ST_st63_fsm_62;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st63_fsm_62))
    {
        ap_NS_fsm = ap_ST_st64_fsm_63;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st64_fsm_63))
    {
        ap_NS_fsm = ap_ST_st65_fsm_64;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st65_fsm_64))
    {
        ap_NS_fsm = ap_ST_st66_fsm_65;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st66_fsm_65))
    {
        ap_NS_fsm = ap_ST_st67_fsm_66;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st67_fsm_66))
    {
        ap_NS_fsm = ap_ST_st68_fsm_67;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st68_fsm_67))
    {
        ap_NS_fsm = ap_ST_st69_fsm_68;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st69_fsm_68))
    {
        ap_NS_fsm = ap_ST_st70_fsm_69;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st70_fsm_69))
    {
        ap_NS_fsm = ap_ST_st71_fsm_70;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st71_fsm_70))
    {
        ap_NS_fsm = ap_ST_st72_fsm_71;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st72_fsm_71))
    {
        ap_NS_fsm = ap_ST_st73_fsm_72;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st73_fsm_72))
    {
        ap_NS_fsm = ap_ST_st74_fsm_73;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st74_fsm_73))
    {
        ap_NS_fsm = ap_ST_st75_fsm_74;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st75_fsm_74))
    {
        ap_NS_fsm = ap_ST_st76_fsm_75;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st76_fsm_75))
    {
        ap_NS_fsm = ap_ST_st77_fsm_76;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st77_fsm_76))
    {
        ap_NS_fsm = ap_ST_st78_fsm_77;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st78_fsm_77))
    {
        ap_NS_fsm = ap_ST_st79_fsm_78;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st79_fsm_78))
    {
        ap_NS_fsm = ap_ST_st80_fsm_79;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st80_fsm_79))
    {
        ap_NS_fsm = ap_ST_st81_fsm_80;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st81_fsm_80))
    {
        ap_NS_fsm = ap_ST_st82_fsm_81;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st82_fsm_81))
    {
        ap_NS_fsm = ap_ST_st83_fsm_82;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st83_fsm_82))
    {
        ap_NS_fsm = ap_ST_st84_fsm_83;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st84_fsm_83))
    {
        ap_NS_fsm = ap_ST_st85_fsm_84;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st85_fsm_84))
    {
        ap_NS_fsm = ap_ST_st86_fsm_85;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st86_fsm_85))
    {
        ap_NS_fsm = ap_ST_st87_fsm_86;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st87_fsm_86))
    {
        ap_NS_fsm = ap_ST_st88_fsm_87;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st88_fsm_87))
    {
        ap_NS_fsm = ap_ST_st89_fsm_88;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st89_fsm_88))
    {
        ap_NS_fsm = ap_ST_st90_fsm_89;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st90_fsm_89))
    {
        ap_NS_fsm = ap_ST_st91_fsm_90;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st91_fsm_90))
    {
        ap_NS_fsm = ap_ST_st92_fsm_91;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st92_fsm_91))
    {
        ap_NS_fsm = ap_ST_st93_fsm_92;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st93_fsm_92))
    {
        ap_NS_fsm = ap_ST_st94_fsm_93;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st94_fsm_93))
    {
        ap_NS_fsm = ap_ST_st95_fsm_94;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st95_fsm_94))
    {
        ap_NS_fsm = ap_ST_st96_fsm_95;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st96_fsm_95))
    {
        ap_NS_fsm = ap_ST_st97_fsm_96;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st97_fsm_96))
    {
        ap_NS_fsm = ap_ST_st98_fsm_97;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st98_fsm_97))
    {
        ap_NS_fsm = ap_ST_st99_fsm_98;
    }
    else if (esl_seteq<1,99,99>(ap_CS_fsm.read(), ap_ST_st99_fsm_98))
    {
        ap_NS_fsm = ap_ST_st48_fsm_47;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<99>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

