// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "obj_detector_FCL.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic obj_detector_FCL::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic obj_detector_FCL::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> obj_detector_FCL::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> obj_detector_FCL::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<6> obj_detector_FCL::ap_ST_pp0_stg1_fsm_2 = "100";
const sc_lv<6> obj_detector_FCL::ap_ST_pp0_stg2_fsm_3 = "1000";
const sc_lv<6> obj_detector_FCL::ap_ST_pp0_stg3_fsm_4 = "10000";
const sc_lv<6> obj_detector_FCL::ap_ST_st9_fsm_5 = "100000";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> obj_detector_FCL::ap_const_lv1_1 = "1";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_1 = "1";
const sc_lv<1> obj_detector_FCL::ap_const_lv1_0 = "0";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_2 = "10";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_3 = "11";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_4 = "100";
const sc_lv<10> obj_detector_FCL::ap_const_lv10_0 = "0000000000";
const sc_lv<11> obj_detector_FCL::ap_const_lv11_360 = "1101100000";
const sc_lv<11> obj_detector_FCL::ap_const_lv11_0 = "00000000000";
const sc_lv<10> obj_detector_FCL::ap_const_lv10_360 = "1101100000";
const sc_lv<10> obj_detector_FCL::ap_const_lv10_1 = "1";
const sc_lv<32> obj_detector_FCL::ap_const_lv32_5 = "101";
const sc_lv<4> obj_detector_FCL::ap_const_lv4_0 = "0000";

obj_detector_FCL::obj_detector_FCL(sc_module_name name) : sc_module(name), mVcdFile(0) {
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49 = new obj_detector_fadd_32ns_32ns_32_4_full_dsp<1,4,32,32,32>("obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49");
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->clk(ap_clk);
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->reset(ap_rst);
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->din0(grp_fu_99_p0);
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->din1(grp_fu_99_p1);
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->ce(grp_fu_99_ce);
    obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49->dout(grp_fu_99_p2);
    obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50 = new obj_detector_fmul_32ns_32ns_32_1_max_dsp<1,1,32,32,32>("obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50");
    obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50->din0(tmp_s_fu_104_p0);
    obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50->din1(tmp_s_fu_104_p1);
    obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50->dout(tmp_s_fu_104_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_W_Addr_A);
    sensitive << ( W_Addr_A_orig );

    SC_METHOD(thread_W_Addr_A_orig);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_16_fu_142_p1 );

    SC_METHOD(thread_W_Din_A);

    SC_METHOD(thread_W_EN_A);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_W_WEN_A);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_5 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_5 );

    SC_METHOD(thread_ap_return);
    sensitive << ( out_reg_76 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_5 );

    SC_METHOD(thread_ap_sig_bdd_112);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_170);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_97);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_bdd_61 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_2);
    sensitive << ( ap_sig_bdd_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg2_fsm_3);
    sensitive << ( ap_sig_bdd_97 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg3_fsm_4);
    sensitive << ( ap_sig_bdd_112 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_24 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_5);
    sensitive << ( ap_sig_bdd_170 );

    SC_METHOD(thread_exitcond_fu_116_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( i_phi_fu_92_p4 );

    SC_METHOD(thread_grp_fu_99_ce);

    SC_METHOD(thread_grp_fu_99_p0);
    sensitive << ( out_reg_76 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );

    SC_METHOD(thread_grp_fu_99_p1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_s_reg_181 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );

    SC_METHOD(thread_i_5_fu_122_p2);
    sensitive << ( i_phi_fu_92_p4 );

    SC_METHOD(thread_i_phi_fu_92_p4);
    sensitive << ( i_reg_88 );
    sensitive << ( exitcond_reg_152 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( i_5_reg_156 );

    SC_METHOD(thread_inp_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_fu_128_p1 );

    SC_METHOD(thread_inp_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_p_addr1_fu_137_p2);
    sensitive << ( tmp_16_cast_reg_147 );
    sensitive << ( tmp_trn_cast_fu_133_p1 );

    SC_METHOD(thread_tmp_16_cast_fu_108_p3);
    sensitive << ( W_offset );

    SC_METHOD(thread_tmp_16_fu_142_p1);
    sensitive << ( p_addr1_fu_137_p2 );

    SC_METHOD(thread_tmp_fu_128_p1);
    sensitive << ( i_phi_fu_92_p4 );

    SC_METHOD(thread_tmp_s_fu_104_p0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( inp_load_reg_171 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_tmp_s_fu_104_p1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( W_load_reg_176 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_tmp_trn_cast_fu_133_p1);
    sensitive << ( i_phi_fu_92_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_116_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    ap_CS_fsm = "000001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "obj_detector_FCL_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inp_address0, "(port)inp_address0");
    sc_trace(mVcdFile, inp_ce0, "(port)inp_ce0");
    sc_trace(mVcdFile, inp_q0, "(port)inp_q0");
    sc_trace(mVcdFile, W_Addr_A, "(port)W_Addr_A");
    sc_trace(mVcdFile, W_EN_A, "(port)W_EN_A");
    sc_trace(mVcdFile, W_WEN_A, "(port)W_WEN_A");
    sc_trace(mVcdFile, W_Din_A, "(port)W_Din_A");
    sc_trace(mVcdFile, W_Dout_A, "(port)W_Dout_A");
    sc_trace(mVcdFile, W_offset, "(port)W_offset");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_24, "ap_sig_bdd_24");
    sc_trace(mVcdFile, out_reg_76, "out_reg_76");
    sc_trace(mVcdFile, i_reg_88, "i_reg_88");
    sc_trace(mVcdFile, tmp_16_cast_fu_108_p3, "tmp_16_cast_fu_108_p3");
    sc_trace(mVcdFile, tmp_16_cast_reg_147, "tmp_16_cast_reg_147");
    sc_trace(mVcdFile, exitcond_fu_116_p2, "exitcond_fu_116_p2");
    sc_trace(mVcdFile, exitcond_reg_152, "exitcond_reg_152");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_61, "ap_sig_bdd_61");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_152_pp0_it1, "ap_reg_ppstg_exitcond_reg_152_pp0_it1");
    sc_trace(mVcdFile, i_5_fu_122_p2, "i_5_fu_122_p2");
    sc_trace(mVcdFile, i_5_reg_156, "i_5_reg_156");
    sc_trace(mVcdFile, inp_load_reg_171, "inp_load_reg_171");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_2, "ap_sig_cseq_ST_pp0_stg1_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_85, "ap_sig_bdd_85");
    sc_trace(mVcdFile, W_load_reg_176, "W_load_reg_176");
    sc_trace(mVcdFile, tmp_s_fu_104_p2, "tmp_s_fu_104_p2");
    sc_trace(mVcdFile, tmp_s_reg_181, "tmp_s_reg_181");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg2_fsm_3, "ap_sig_cseq_ST_pp0_stg2_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_97, "ap_sig_bdd_97");
    sc_trace(mVcdFile, grp_fu_99_p2, "grp_fu_99_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg3_fsm_4, "ap_sig_cseq_ST_pp0_stg3_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_112, "ap_sig_bdd_112");
    sc_trace(mVcdFile, i_phi_fu_92_p4, "i_phi_fu_92_p4");
    sc_trace(mVcdFile, tmp_fu_128_p1, "tmp_fu_128_p1");
    sc_trace(mVcdFile, tmp_16_fu_142_p1, "tmp_16_fu_142_p1");
    sc_trace(mVcdFile, W_Addr_A_orig, "W_Addr_A_orig");
    sc_trace(mVcdFile, grp_fu_99_p0, "grp_fu_99_p0");
    sc_trace(mVcdFile, grp_fu_99_p1, "grp_fu_99_p1");
    sc_trace(mVcdFile, tmp_s_fu_104_p0, "tmp_s_fu_104_p0");
    sc_trace(mVcdFile, tmp_s_fu_104_p1, "tmp_s_fu_104_p1");
    sc_trace(mVcdFile, tmp_trn_cast_fu_133_p1, "tmp_trn_cast_fu_133_p1");
    sc_trace(mVcdFile, p_addr1_fu_137_p2, "p_addr1_fu_137_p2");
    sc_trace(mVcdFile, grp_fu_99_ce, "grp_fu_99_ce");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_5, "ap_sig_cseq_ST_st9_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_170, "ap_sig_bdd_170");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

obj_detector_FCL::~obj_detector_FCL() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete obj_detector_fadd_32ns_32ns_32_4_full_dsp_U49;
    delete obj_detector_fmul_32ns_32ns_32_1_max_dsp_U50;
}

void obj_detector_FCL::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_fu_116_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()) && 
                     !esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0))) {
        i_reg_88 = i_5_reg_156.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_88 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_reg_152_pp0_it1.read(), ap_const_lv1_0))) {
        out_reg_76 = grp_fu_99_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        out_reg_76 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0))) {
        W_load_reg_176 = W_Dout_A.read();
        inp_load_reg_171 = inp_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond_reg_152_pp0_it1 = exitcond_reg_152.read();
        exitcond_reg_152 = exitcond_fu_116_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        i_5_reg_156 = i_5_fu_122_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_16_cast_reg_147 = tmp_16_cast_fu_108_p3.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        tmp_s_reg_181 = tmp_s_fu_104_p2.read();
    }
}

void obj_detector_FCL::thread_W_Addr_A() {
    W_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): W_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void obj_detector_FCL::thread_W_Addr_A_orig() {
    W_Addr_A_orig =  (sc_lv<32>) (tmp_16_fu_142_p1.read());
}

void obj_detector_FCL::thread_W_Din_A() {
    W_Din_A = ap_const_lv32_0;
}

void obj_detector_FCL::thread_W_EN_A() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        W_EN_A = ap_const_logic_1;
    } else {
        W_EN_A = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_W_WEN_A() {
    W_WEN_A = ap_const_lv4_0;
}

void obj_detector_FCL::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_return() {
    ap_return = out_reg_76.read();
}

void obj_detector_FCL::thread_ap_sig_bdd_112() {
    ap_sig_bdd_112 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void obj_detector_FCL::thread_ap_sig_bdd_170() {
    ap_sig_bdd_170 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void obj_detector_FCL::thread_ap_sig_bdd_24() {
    ap_sig_bdd_24 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void obj_detector_FCL::thread_ap_sig_bdd_61() {
    ap_sig_bdd_61 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void obj_detector_FCL::thread_ap_sig_bdd_85() {
    ap_sig_bdd_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void obj_detector_FCL::thread_ap_sig_bdd_97() {
    ap_sig_bdd_97 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_bdd_61.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_pp0_stg1_fsm_2() {
    if (ap_sig_bdd_85.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_pp0_stg2_fsm_3() {
    if (ap_sig_bdd_97.read()) {
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_pp0_stg3_fsm_4() {
    if (ap_sig_bdd_112.read()) {
        ap_sig_cseq_ST_pp0_stg3_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg3_fsm_4 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_24.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_ap_sig_cseq_ST_st9_fsm_5() {
    if (ap_sig_bdd_170.read()) {
        ap_sig_cseq_ST_st9_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_5 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_exitcond_fu_116_p2() {
    exitcond_fu_116_p2 = (!i_phi_fu_92_p4.read().is_01() || !ap_const_lv10_360.is_01())? sc_lv<1>(): sc_lv<1>(i_phi_fu_92_p4.read() == ap_const_lv10_360);
}

void obj_detector_FCL::thread_grp_fu_99_ce() {
    grp_fu_99_ce = ap_const_logic_1;
}

void obj_detector_FCL::thread_grp_fu_99_p0() {
    grp_fu_99_p0 = out_reg_76.read();
}

void obj_detector_FCL::thread_grp_fu_99_p1() {
    grp_fu_99_p1 = tmp_s_reg_181.read();
}

void obj_detector_FCL::thread_i_5_fu_122_p2() {
    i_5_fu_122_p2 = (!i_phi_fu_92_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_phi_fu_92_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void obj_detector_FCL::thread_i_phi_fu_92_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_152.read(), ap_const_lv1_0))) {
        i_phi_fu_92_p4 = i_5_reg_156.read();
    } else {
        i_phi_fu_92_p4 = i_reg_88.read();
    }
}

void obj_detector_FCL::thread_inp_address0() {
    inp_address0 =  (sc_lv<10>) (tmp_fu_128_p1.read());
}

void obj_detector_FCL::thread_inp_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        inp_ce0 = ap_const_logic_1;
    } else {
        inp_ce0 = ap_const_logic_0;
    }
}

void obj_detector_FCL::thread_p_addr1_fu_137_p2() {
    p_addr1_fu_137_p2 = (!tmp_trn_cast_fu_133_p1.read().is_01() || !tmp_16_cast_reg_147.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_trn_cast_fu_133_p1.read()) + sc_biguint<11>(tmp_16_cast_reg_147.read()));
}

void obj_detector_FCL::thread_tmp_16_cast_fu_108_p3() {
    tmp_16_cast_fu_108_p3 = (!W_offset.read()[0].is_01())? sc_lv<11>(): ((W_offset.read()[0].to_bool())? ap_const_lv11_360: ap_const_lv11_0);
}

void obj_detector_FCL::thread_tmp_16_fu_142_p1() {
    tmp_16_fu_142_p1 = esl_zext<64,11>(p_addr1_fu_137_p2.read());
}

void obj_detector_FCL::thread_tmp_fu_128_p1() {
    tmp_fu_128_p1 = esl_zext<64,10>(i_phi_fu_92_p4.read());
}

void obj_detector_FCL::thread_tmp_s_fu_104_p0() {
    tmp_s_fu_104_p0 = inp_load_reg_171.read();
}

void obj_detector_FCL::thread_tmp_s_fu_104_p1() {
    tmp_s_fu_104_p1 = W_load_reg_176.read();
}

void obj_detector_FCL::thread_tmp_trn_cast_fu_133_p1() {
    tmp_trn_cast_fu_133_p1 = esl_zext<11,10>(i_phi_fu_92_p4.read());
}

void obj_detector_FCL::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_fu_116_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_5;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_3;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg3_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

