#pragma line 1 "proj1_hls/obj_detector.cpp" ::: 0
#pragma line 1 "proj1_hls/obj_detector.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 404 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 195
#pragma line 6 "<command line>" 2 ::: 198
#pragma line 1 "<built-in>" 2 ::: 199
#pragma line 1 "proj1_hls/obj_detector.cpp" 2 ::: 200
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 201
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 228
#pragma line 122 "/usr/include/features.h" 3 4 ::: 325
#pragma line 156 "/usr/include/features.h" 3 4 ::: 350
#pragma line 180 "/usr/include/features.h" 3 4 ::: 352
#pragma line 191 "/usr/include/features.h" 3 4 ::: 355
#pragma line 343 "/usr/include/features.h" 3 4 ::: 386
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 390
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 425
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 432
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 455
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 496
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 502
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 532
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 536
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 546
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 599
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 640
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 665
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 689
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 690
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 692
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 694
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 695
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 720
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 731
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 736
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 737
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 738
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 744
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 770
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 802
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 803
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 808
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 833
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 835
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 860
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 861
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 880
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 884
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 908
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 912
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 937
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 942
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 959
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 965
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 972
#pragma line 83 "/usr/include/math.h" 3 4 ::: 978
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 979
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1363
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1364
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1367
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1368
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1752
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1753
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1756
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1757
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2141
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2142
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2209
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2211
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2213
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2223
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2225
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2241
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2295
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2297
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2301
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2316
#pragma line 534 "/usr/include/math.h" 3 4 ::: 2372
#pragma line 2 "proj1_hls/obj_detector.cpp" 2 ::: 2374
#pragma line 1 "proj1_hls/obj_detector.h" 1 ::: 2376
#pragma line 11 "proj1_hls/obj_detector.h" ::: 2377
#pragma line 4 "proj1_hls/obj_detector.cpp" 2 ::: 2385
