#pragma line 1 "proj1_hls/obj_detector.cpp" ::: -10
#pragma line 1 "proj1_hls/obj_detector.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 404 "/home/littlefoot/vivado/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 185
#pragma line 6 "<command line>" 2 ::: 188
#pragma line 1 "<built-in>" 2 ::: 189
#pragma line 1 "proj1_hls/obj_detector.cpp" 2 ::: 190
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 192
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 219
#pragma line 122 "/usr/include/features.h" 3 4 ::: 316
#pragma line 156 "/usr/include/features.h" 3 4 ::: 341
#pragma line 180 "/usr/include/features.h" 3 4 ::: 343
#pragma line 191 "/usr/include/features.h" 3 4 ::: 346
#pragma line 343 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 423
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 446
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 487
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 493
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 511
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 590
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 631
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 656
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 680
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 681
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 683
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 685
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 686
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 711
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 722
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 727
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 728
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 729
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 735
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 761
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 793
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 794
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 799
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 824
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 826
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 851
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 852
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 871
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 875
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 899
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 903
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 928
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 933
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 950
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 956
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 963
#pragma line 83 "/usr/include/math.h" 3 4 ::: 969
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 970
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1354
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1355
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1358
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1359
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1743
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1744
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1747
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1748
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2132
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2133
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2200
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2202
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2204
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2214
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2216
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2232
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2286
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2288
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2292
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2307
#pragma line 534 "/usr/include/math.h" 3 4 ::: 2363
#pragma line 2 "proj1_hls/obj_detector.cpp" 2 ::: 2365
#pragma line 2 "proj1_hls/obj_detector.cpp" ::: 2367
#pragma line 1 "proj1_hls/obj_detector.h" 1 ::: 2370
#pragma line 11 "proj1_hls/obj_detector.h" ::: 2371
#pragma line 4 "proj1_hls/obj_detector.cpp" 2 ::: 2379
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2390
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2393
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2396
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2399
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2402
#pragma line 12 "proj1_hls/obj_detector.cpp" ::: 2405
#pragma line 59 "proj1_hls/obj_detector.cpp" ::: 2455
#pragma line 66 "proj1_hls/obj_detector.cpp" ::: 2465
#pragma line 95 "proj1_hls/obj_detector.cpp" ::: 2497
#pragma line 124 "proj1_hls/obj_detector.cpp" ::: 2529
#pragma line 135 "proj1_hls/obj_detector.cpp" ::: 2543
