lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "UNROLL" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "convolve/convolve_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "RESOURCE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "A"}
lappend pragmaStatus6 {pragma "RESOURCE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "obj_detector" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "W0"}
lappend pragmaStatus7 {pragma "PIPELINE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "convolve/convolve_label5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "maxpool/maxpool_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "flatten/flatten_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "C:/Users/sunny/Google_Drive/CMU/Courses/CMU/18643/vivado_projects/proj1_hls/obj_detector.cpp" location "FCL/FCL_label8" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
