// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"

#include "hls_stream.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "input_V"
#define AUTOTB_TVIN_input_V  "../tv/cdatafile/c.splitter.autotvin_input_V.dat"
#define WRAPC_STREAM_SIZE_IN_input_V  "../tv/stream_size/stream_size_in_input_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_input_V  "../tv/stream_size/stream_ingress_status_input_V.dat"
// wrapc file define: "output_0_V"
#define AUTOTB_TVOUT_output_0_V  "../tv/cdatafile/c.splitter.autotvout_output_0_V.dat"
#define AUTOTB_TVIN_output_0_V  "../tv/cdatafile/c.splitter.autotvin_output_0_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_0_V  "../tv/stream_size/stream_size_out_output_0_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_0_V  "../tv/stream_size/stream_egress_status_output_0_V.dat"
// wrapc file define: "output_1_V"
#define AUTOTB_TVOUT_output_1_V  "../tv/cdatafile/c.splitter.autotvout_output_1_V.dat"
#define AUTOTB_TVIN_output_1_V  "../tv/cdatafile/c.splitter.autotvin_output_1_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_1_V  "../tv/stream_size/stream_size_out_output_1_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_1_V  "../tv/stream_size/stream_egress_status_output_1_V.dat"
// wrapc file define: "output_2_V"
#define AUTOTB_TVOUT_output_2_V  "../tv/cdatafile/c.splitter.autotvout_output_2_V.dat"
#define AUTOTB_TVIN_output_2_V  "../tv/cdatafile/c.splitter.autotvin_output_2_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_2_V  "../tv/stream_size/stream_size_out_output_2_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_2_V  "../tv/stream_size/stream_egress_status_output_2_V.dat"
// wrapc file define: "output_3_V"
#define AUTOTB_TVOUT_output_3_V  "../tv/cdatafile/c.splitter.autotvout_output_3_V.dat"
#define AUTOTB_TVIN_output_3_V  "../tv/cdatafile/c.splitter.autotvin_output_3_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_3_V  "../tv/stream_size/stream_size_out_output_3_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_3_V  "../tv/stream_size/stream_egress_status_output_3_V.dat"
// wrapc file define: "output_4_V"
#define AUTOTB_TVOUT_output_4_V  "../tv/cdatafile/c.splitter.autotvout_output_4_V.dat"
#define AUTOTB_TVIN_output_4_V  "../tv/cdatafile/c.splitter.autotvin_output_4_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_4_V  "../tv/stream_size/stream_size_out_output_4_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_4_V  "../tv/stream_size/stream_egress_status_output_4_V.dat"
// wrapc file define: "output_5_V"
#define AUTOTB_TVOUT_output_5_V  "../tv/cdatafile/c.splitter.autotvout_output_5_V.dat"
#define AUTOTB_TVIN_output_5_V  "../tv/cdatafile/c.splitter.autotvin_output_5_V.dat"
#define WRAPC_STREAM_SIZE_OUT_output_5_V  "../tv/stream_size/stream_size_out_output_5_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_output_5_V  "../tv/stream_size/stream_egress_status_output_5_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "output_0_V"
#define AUTOTB_TVOUT_PC_output_0_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_0_V.dat"
// tvout file define: "output_1_V"
#define AUTOTB_TVOUT_PC_output_1_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_1_V.dat"
// tvout file define: "output_2_V"
#define AUTOTB_TVOUT_PC_output_2_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_2_V.dat"
// tvout file define: "output_3_V"
#define AUTOTB_TVOUT_PC_output_3_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_3_V.dat"
// tvout file define: "output_4_V"
#define AUTOTB_TVOUT_PC_output_4_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_4_V.dat"
// tvout file define: "output_5_V"
#define AUTOTB_TVOUT_PC_output_5_V  "../tv/rtldatafile/rtl.splitter.autotvout_output_5_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			input_V_depth = 0;
			output_0_V_depth = 0;
			output_1_V_depth = 0;
			output_2_V_depth = 0;
			output_3_V_depth = 0;
			output_4_V_depth = 0;
			output_5_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{input_V " << input_V_depth << "}\n";
			total_list << "{output_0_V " << output_0_V_depth << "}\n";
			total_list << "{output_1_V " << output_1_V_depth << "}\n";
			total_list << "{output_2_V " << output_2_V_depth << "}\n";
			total_list << "{output_3_V " << output_3_V_depth << "}\n";
			total_list << "{output_4_V " << output_4_V_depth << "}\n";
			total_list << "{output_5_V " << output_5_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int input_V_depth;
		int output_0_V_depth;
		int output_1_V_depth;
		int output_2_V_depth;
		int output_3_V_depth;
		int output_4_V_depth;
		int output_5_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define splitter AESL_ORIG_DUT_splitter
extern void splitter (hls::stream< unsigned char >& input, hls::stream< unsigned char > output[6]);
#undef splitter

void splitter (hls::stream< unsigned char >& input, hls::stream< unsigned char > output[6])
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "input"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_input_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_input_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_input_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				input.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_input_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[0]"
		std::vector< unsigned char > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "output[0]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[1]"
		std::vector< unsigned char > aesl_tmp_6;
		int aesl_tmp_7;
		int aesl_tmp_8 = 0;

		// read output stream size: "output[1]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_7 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[2]"
		std::vector< unsigned char > aesl_tmp_9;
		int aesl_tmp_10;
		int aesl_tmp_11 = 0;

		// read output stream size: "output[2]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_10 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[3]"
		std::vector< unsigned char > aesl_tmp_12;
		int aesl_tmp_13;
		int aesl_tmp_14 = 0;

		// read output stream size: "output[3]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_13 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[4]"
		std::vector< unsigned char > aesl_tmp_15;
		int aesl_tmp_16;
		int aesl_tmp_17 = 0;

		// read output stream size: "output[4]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_16 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "output[5]"
		std::vector< unsigned char > aesl_tmp_18;
		int aesl_tmp_19;
		int aesl_tmp_20 = 0;

		// read output stream size: "output[5]"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // pop_size
			aesl_tmp_19 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_output_0_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "output_0_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_0_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_0_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_0_V, AESL_token); // data

			std::vector<sc_bv<8> > output_0_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_0_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_0_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_0_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_0_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_0_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					 unsigned char tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_0_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_0_0_2 = new sc_lv<8>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_4 - aesl_tmp_5 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_0_0_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_0_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_4 - aesl_tmp_5 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_3[i_0] = (output_V_lv0_0_0_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "output_1_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_1_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_1_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_1_V, AESL_token); // data

			std::vector<sc_bv<8> > output_1_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_1_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_1_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_1_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_1_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_1_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_7)
			{
				aesl_tmp_7 = i;
			}

			if (aesl_tmp_7 > 0 && aesl_tmp_6.size() < aesl_tmp_7)
			{
				int aesl_tmp_6_size = aesl_tmp_6.size();

				for (int tmp_aesl_tmp_6 = 0; tmp_aesl_tmp_6 < aesl_tmp_7 - aesl_tmp_6_size; tmp_aesl_tmp_6++)
				{
					 unsigned char tmp;
					aesl_tmp_6.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_1_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_1_1_2 = new sc_lv<8>[aesl_tmp_7 - aesl_tmp_8];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_7 - aesl_tmp_8 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_7 - aesl_tmp_8 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_6[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_1_1_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_1_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_7 - aesl_tmp_8 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_7 - aesl_tmp_8 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_6[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_6[i_0] = (output_V_lv0_1_1_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "output_2_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_2_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_2_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_2_V, AESL_token); // data

			std::vector<sc_bv<8> > output_2_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_2_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_2_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_2_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_2_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_2_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_10)
			{
				aesl_tmp_10 = i;
			}

			if (aesl_tmp_10 > 0 && aesl_tmp_9.size() < aesl_tmp_10)
			{
				int aesl_tmp_9_size = aesl_tmp_9.size();

				for (int tmp_aesl_tmp_9 = 0; tmp_aesl_tmp_9 < aesl_tmp_10 - aesl_tmp_9_size; tmp_aesl_tmp_9++)
				{
					 unsigned char tmp;
					aesl_tmp_9.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_2_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_2_2_2 = new sc_lv<8>[aesl_tmp_10 - aesl_tmp_11];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_10 - aesl_tmp_11 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_10 - aesl_tmp_11 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_2_2_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_2_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_10 - aesl_tmp_11 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_10 - aesl_tmp_11 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_9[i_0] = (output_V_lv0_2_2_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "output_3_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_3_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_3_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_3_V, AESL_token); // data

			std::vector<sc_bv<8> > output_3_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_3_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_3_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_3_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_3_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_3_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_13)
			{
				aesl_tmp_13 = i;
			}

			if (aesl_tmp_13 > 0 && aesl_tmp_12.size() < aesl_tmp_13)
			{
				int aesl_tmp_12_size = aesl_tmp_12.size();

				for (int tmp_aesl_tmp_12 = 0; tmp_aesl_tmp_12 < aesl_tmp_13 - aesl_tmp_12_size; tmp_aesl_tmp_12++)
				{
					 unsigned char tmp;
					aesl_tmp_12.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_3_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_3_3_2 = new sc_lv<8>[aesl_tmp_13 - aesl_tmp_14];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_13 - aesl_tmp_14 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_13 - aesl_tmp_14 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_12[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_3_3_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_3_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_13 - aesl_tmp_14 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_13 - aesl_tmp_14 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_12[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_12[i_0] = (output_V_lv0_3_3_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "output_4_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_4_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_4_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_4_V, AESL_token); // data

			std::vector<sc_bv<8> > output_4_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_4_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_4_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_4_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_4_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_4_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_16)
			{
				aesl_tmp_16 = i;
			}

			if (aesl_tmp_16 > 0 && aesl_tmp_15.size() < aesl_tmp_16)
			{
				int aesl_tmp_15_size = aesl_tmp_15.size();

				for (int tmp_aesl_tmp_15 = 0; tmp_aesl_tmp_15 < aesl_tmp_16 - aesl_tmp_15_size; tmp_aesl_tmp_15++)
				{
					 unsigned char tmp;
					aesl_tmp_15.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_4_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_4_4_2 = new sc_lv<8>[aesl_tmp_16 - aesl_tmp_17];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_16 - aesl_tmp_17 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_16 - aesl_tmp_17 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_15[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_4_4_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_4_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_16 - aesl_tmp_17 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_16 - aesl_tmp_17 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_15[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_15[i_0] = (output_V_lv0_4_4_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// output port post check: "output_5_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_output_5_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_output_5_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_output_5_V, AESL_token); // data

			std::vector<sc_bv<8> > output_5_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_5_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'output_5_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					output_5_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_output_5_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_output_5_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_19)
			{
				aesl_tmp_19 = i;
			}

			if (aesl_tmp_19 > 0 && aesl_tmp_18.size() < aesl_tmp_19)
			{
				int aesl_tmp_18_size = aesl_tmp_18.size();

				for (int tmp_aesl_tmp_18 = 0; tmp_aesl_tmp_18 < aesl_tmp_19 - aesl_tmp_18_size; tmp_aesl_tmp_18++)
				{
					 unsigned char tmp;
					aesl_tmp_18.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: output_5_V
				{
					// bitslice(7, 0)
					// {
						// celement: output.V(7, 0)
						// {
							sc_lv<8>* output_V_lv0_5_5_2 = new sc_lv<8>[aesl_tmp_19 - aesl_tmp_20];
						// }
					// }

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_19 - aesl_tmp_20 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_19 - aesl_tmp_20 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_18[0]) != NULL) // check the null address if the c port is array or others
								{
									output_V_lv0_5_5_2[hls_map_index++].range(7, 0) = sc_bv<8>(output_5_V_pc_buffer[hls_map_index].range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						int hls_map_index = 0;
						// celement: output.V(7, 0)
						{
							// carray: (0) => (aesl_tmp_19 - aesl_tmp_20 - 1) @ (1)
							for (int i_0 = 0; i_0 <= aesl_tmp_19 - aesl_tmp_20 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_18[0]) != NULL) // check the null address if the c port is array or others
								{
									aesl_tmp_18[i_0] = (output_V_lv0_5_5_2[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "output[0]"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			output[0].write(aesl_tmp_3[i]);
		}

		// push back output stream: "output[1]"
		for (int i = 0; i < aesl_tmp_7; i++)
		{
			output[1].write(aesl_tmp_6[i]);
		}

		// push back output stream: "output[2]"
		for (int i = 0; i < aesl_tmp_10; i++)
		{
			output[2].write(aesl_tmp_9[i]);
		}

		// push back output stream: "output[3]"
		for (int i = 0; i < aesl_tmp_13; i++)
		{
			output[3].write(aesl_tmp_12[i]);
		}

		// push back output stream: "output[4]"
		for (int i = 0; i < aesl_tmp_16; i++)
		{
			output[4].write(aesl_tmp_15[i]);
		}

		// push back output stream: "output[5]"
		for (int i = 0; i < aesl_tmp_19; i++)
		{
			output[5].write(aesl_tmp_18[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "input_V"
		char* tvin_input_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_input_V);
		char* wrapc_stream_size_in_input_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_input_V);
		char* wrapc_stream_ingress_status_input_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_input_V);

		// "output_0_V"
		char* tvin_output_0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_0_V);
		char* tvout_output_0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_0_V);
		char* wrapc_stream_size_out_output_0_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_0_V);
		char* wrapc_stream_egress_status_output_0_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_0_V);

		// "output_1_V"
		char* tvin_output_1_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_1_V);
		char* tvout_output_1_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_1_V);
		char* wrapc_stream_size_out_output_1_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_1_V);
		char* wrapc_stream_egress_status_output_1_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_1_V);

		// "output_2_V"
		char* tvin_output_2_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_2_V);
		char* tvout_output_2_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_2_V);
		char* wrapc_stream_size_out_output_2_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_2_V);
		char* wrapc_stream_egress_status_output_2_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_2_V);

		// "output_3_V"
		char* tvin_output_3_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_3_V);
		char* tvout_output_3_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_3_V);
		char* wrapc_stream_size_out_output_3_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_3_V);
		char* wrapc_stream_egress_status_output_3_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_3_V);

		// "output_4_V"
		char* tvin_output_4_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_4_V);
		char* tvout_output_4_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_4_V);
		char* wrapc_stream_size_out_output_4_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_4_V);
		char* wrapc_stream_egress_status_output_4_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_4_V);

		// "output_5_V"
		char* tvin_output_5_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_output_5_V);
		char* tvout_output_5_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_output_5_V);
		char* wrapc_stream_size_out_output_5_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_output_5_V);
		char* wrapc_stream_egress_status_output_5_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_output_5_V);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "input"
		std::vector< unsigned char > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!input.empty())
		{
			aesl_tmp_0.push_back(input.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "output[0]"
		std::vector< unsigned char > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!output[0].empty())
		{
			aesl_tmp_3.push_back(output[0].read());
			aesl_tmp_4++;
		}

		// dump stream tvin: "output[1]"
		std::vector< unsigned char > aesl_tmp_6;
		int aesl_tmp_7 = 0;
		while (!output[1].empty())
		{
			aesl_tmp_6.push_back(output[1].read());
			aesl_tmp_7++;
		}

		// dump stream tvin: "output[2]"
		std::vector< unsigned char > aesl_tmp_9;
		int aesl_tmp_10 = 0;
		while (!output[2].empty())
		{
			aesl_tmp_9.push_back(output[2].read());
			aesl_tmp_10++;
		}

		// dump stream tvin: "output[3]"
		std::vector< unsigned char > aesl_tmp_12;
		int aesl_tmp_13 = 0;
		while (!output[3].empty())
		{
			aesl_tmp_12.push_back(output[3].read());
			aesl_tmp_13++;
		}

		// dump stream tvin: "output[4]"
		std::vector< unsigned char > aesl_tmp_15;
		int aesl_tmp_16 = 0;
		while (!output[4].empty())
		{
			aesl_tmp_15.push_back(output[4].read());
			aesl_tmp_16++;
		}

		// dump stream tvin: "output[5]"
		std::vector< unsigned char > aesl_tmp_18;
		int aesl_tmp_19 = 0;
		while (!output[5].empty())
		{
			aesl_tmp_18.push_back(output[5].read());
			aesl_tmp_19++;
		}

		// push back input stream: "input"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			input.write(aesl_tmp_0[i]);
		}

// [call_c_dut] ---------->

		AESL_ORIG_DUT_splitter(input, output);

		// record input size to tv3: "input"
		int aesl_tmp_2 = input.size();

		// pop output stream: "output[0]"
		int aesl_tmp_5 = aesl_tmp_4;
		while (!output[0].empty())
		{
			aesl_tmp_3.push_back(output[0].read());
			aesl_tmp_4++;
		}

		// pop output stream: "output[1]"
		int aesl_tmp_8 = aesl_tmp_7;
		while (!output[1].empty())
		{
			aesl_tmp_6.push_back(output[1].read());
			aesl_tmp_7++;
		}

		// pop output stream: "output[2]"
		int aesl_tmp_11 = aesl_tmp_10;
		while (!output[2].empty())
		{
			aesl_tmp_9.push_back(output[2].read());
			aesl_tmp_10++;
		}

		// pop output stream: "output[3]"
		int aesl_tmp_14 = aesl_tmp_13;
		while (!output[3].empty())
		{
			aesl_tmp_12.push_back(output[3].read());
			aesl_tmp_13++;
		}

		// pop output stream: "output[4]"
		int aesl_tmp_17 = aesl_tmp_16;
		while (!output[4].empty())
		{
			aesl_tmp_15.push_back(output[4].read());
			aesl_tmp_16++;
		}

		// pop output stream: "output[5]"
		int aesl_tmp_20 = aesl_tmp_19;
		while (!output[5].empty())
		{
			aesl_tmp_18.push_back(output[5].read());
			aesl_tmp_19++;
		}

		// [[transaction]]
		sprintf(tvin_input_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_input_V, tvin_input_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, tvin_input_V);

		sc_bv<8>* input_V_tvin_wrapc_buffer = new sc_bv<8>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: input_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: input.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> input_V_tmp_mem;
							input_V_tmp_mem = aesl_tmp_0[i_0];
							input_V_tvin_wrapc_buffer[hls_map_index++].range(7, 0) = input_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_input_V, "%s\n", (input_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_input_V, tvin_input_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_input_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, stream_ingress_size_input_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_input_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, stream_ingress_size_input_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.input_V_depth);
		sprintf(tvin_input_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_input_V, tvin_input_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_input_V, tvin_input_V);

		// release memory allocation
		delete [] input_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_input_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_input_V, wrapc_stream_size_in_input_V);
		sprintf(wrapc_stream_size_in_input_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_input_V, wrapc_stream_size_in_input_V);
		sprintf(wrapc_stream_size_in_input_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_input_V, wrapc_stream_size_in_input_V);

		// [[transaction]]
		sprintf(tvout_output_0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_0_V, tvout_output_0_V);

		sc_bv<8>* output_0_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: output_0_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_4 - aesl_tmp_5 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_4 - aesl_tmp_5 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_3[i_0];
							output_0_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_output_0_V, "%s\n", (output_0_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_0_V, tvout_output_0_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.output_0_V_depth);
		sprintf(tvout_output_0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_0_V, tvout_output_0_V);

		// release memory allocation
		delete [] output_0_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_0_V, wrapc_stream_size_out_output_0_V);
		sprintf(wrapc_stream_size_out_output_0_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_0_V, wrapc_stream_size_out_output_0_V);
		sprintf(wrapc_stream_size_out_output_0_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_0_V, wrapc_stream_size_out_output_0_V);

		// [[transaction]]
		sprintf(tvout_output_1_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_1_V, tvout_output_1_V);

		sc_bv<8>* output_1_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_7 - aesl_tmp_8];

		// RTL Name: output_1_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_7 - aesl_tmp_8 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_7 - aesl_tmp_8 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_6[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_6[i_0];
							output_1_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_7 - aesl_tmp_8; i++)
		{
			sprintf(tvout_output_1_V, "%s\n", (output_1_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_1_V, tvout_output_1_V);
		}

		tcl_file.set_num(aesl_tmp_7 - aesl_tmp_8, &tcl_file.output_1_V_depth);
		sprintf(tvout_output_1_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_1_V, tvout_output_1_V);

		// release memory allocation
		delete [] output_1_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_1_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_1_V, wrapc_stream_size_out_output_1_V);
		sprintf(wrapc_stream_size_out_output_1_V, "%d\n", aesl_tmp_7 - aesl_tmp_8);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_1_V, wrapc_stream_size_out_output_1_V);
		sprintf(wrapc_stream_size_out_output_1_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_1_V, wrapc_stream_size_out_output_1_V);

		// [[transaction]]
		sprintf(tvout_output_2_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_2_V, tvout_output_2_V);

		sc_bv<8>* output_2_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_10 - aesl_tmp_11];

		// RTL Name: output_2_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_10 - aesl_tmp_11 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_10 - aesl_tmp_11 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_9[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_9[i_0];
							output_2_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_10 - aesl_tmp_11; i++)
		{
			sprintf(tvout_output_2_V, "%s\n", (output_2_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_2_V, tvout_output_2_V);
		}

		tcl_file.set_num(aesl_tmp_10 - aesl_tmp_11, &tcl_file.output_2_V_depth);
		sprintf(tvout_output_2_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_2_V, tvout_output_2_V);

		// release memory allocation
		delete [] output_2_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_2_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_2_V, wrapc_stream_size_out_output_2_V);
		sprintf(wrapc_stream_size_out_output_2_V, "%d\n", aesl_tmp_10 - aesl_tmp_11);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_2_V, wrapc_stream_size_out_output_2_V);
		sprintf(wrapc_stream_size_out_output_2_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_2_V, wrapc_stream_size_out_output_2_V);

		// [[transaction]]
		sprintf(tvout_output_3_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_3_V, tvout_output_3_V);

		sc_bv<8>* output_3_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_13 - aesl_tmp_14];

		// RTL Name: output_3_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_13 - aesl_tmp_14 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_13 - aesl_tmp_14 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_12[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_12[i_0];
							output_3_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_13 - aesl_tmp_14; i++)
		{
			sprintf(tvout_output_3_V, "%s\n", (output_3_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_3_V, tvout_output_3_V);
		}

		tcl_file.set_num(aesl_tmp_13 - aesl_tmp_14, &tcl_file.output_3_V_depth);
		sprintf(tvout_output_3_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_3_V, tvout_output_3_V);

		// release memory allocation
		delete [] output_3_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_3_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_3_V, wrapc_stream_size_out_output_3_V);
		sprintf(wrapc_stream_size_out_output_3_V, "%d\n", aesl_tmp_13 - aesl_tmp_14);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_3_V, wrapc_stream_size_out_output_3_V);
		sprintf(wrapc_stream_size_out_output_3_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_3_V, wrapc_stream_size_out_output_3_V);

		// [[transaction]]
		sprintf(tvout_output_4_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_4_V, tvout_output_4_V);

		sc_bv<8>* output_4_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_16 - aesl_tmp_17];

		// RTL Name: output_4_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_16 - aesl_tmp_17 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_16 - aesl_tmp_17 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_15[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_15[i_0];
							output_4_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_16 - aesl_tmp_17; i++)
		{
			sprintf(tvout_output_4_V, "%s\n", (output_4_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_4_V, tvout_output_4_V);
		}

		tcl_file.set_num(aesl_tmp_16 - aesl_tmp_17, &tcl_file.output_4_V_depth);
		sprintf(tvout_output_4_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_4_V, tvout_output_4_V);

		// release memory allocation
		delete [] output_4_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_4_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_4_V, wrapc_stream_size_out_output_4_V);
		sprintf(wrapc_stream_size_out_output_4_V, "%d\n", aesl_tmp_16 - aesl_tmp_17);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_4_V, wrapc_stream_size_out_output_4_V);
		sprintf(wrapc_stream_size_out_output_4_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_4_V, wrapc_stream_size_out_output_4_V);

		// [[transaction]]
		sprintf(tvout_output_5_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_output_5_V, tvout_output_5_V);

		sc_bv<8>* output_5_V_tvout_wrapc_buffer = new sc_bv<8>[aesl_tmp_19 - aesl_tmp_20];

		// RTL Name: output_5_V
		{
			// bitslice(7, 0)
			{
				int hls_map_index = 0;
				// celement: output.V(7, 0)
				{
					// carray: (0) => (aesl_tmp_19 - aesl_tmp_20 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_19 - aesl_tmp_20 - 1; i_0 += 1)
					{
						if (&(aesl_tmp_18[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> output_V_tmp_mem;
							output_V_tmp_mem = aesl_tmp_18[i_0];
							output_5_V_tvout_wrapc_buffer[hls_map_index++].range(7, 0) = output_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_19 - aesl_tmp_20; i++)
		{
			sprintf(tvout_output_5_V, "%s\n", (output_5_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_output_5_V, tvout_output_5_V);
		}

		tcl_file.set_num(aesl_tmp_19 - aesl_tmp_20, &tcl_file.output_5_V_depth);
		sprintf(tvout_output_5_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_output_5_V, tvout_output_5_V);

		// release memory allocation
		delete [] output_5_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_output_5_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_5_V, wrapc_stream_size_out_output_5_V);
		sprintf(wrapc_stream_size_out_output_5_V, "%d\n", aesl_tmp_19 - aesl_tmp_20);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_5_V, wrapc_stream_size_out_output_5_V);
		sprintf(wrapc_stream_size_out_output_5_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_output_5_V, wrapc_stream_size_out_output_5_V);

		// push back output stream: "output[0]"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			output[0].write(aesl_tmp_3[i]);
		}

		// push back output stream: "output[1]"
		for (int i = 0; i < aesl_tmp_7; i++)
		{
			output[1].write(aesl_tmp_6[i]);
		}

		// push back output stream: "output[2]"
		for (int i = 0; i < aesl_tmp_10; i++)
		{
			output[2].write(aesl_tmp_9[i]);
		}

		// push back output stream: "output[3]"
		for (int i = 0; i < aesl_tmp_13; i++)
		{
			output[3].write(aesl_tmp_12[i]);
		}

		// push back output stream: "output[4]"
		for (int i = 0; i < aesl_tmp_16; i++)
		{
			output[4].write(aesl_tmp_15[i]);
		}

		// push back output stream: "output[5]"
		for (int i = 0; i < aesl_tmp_19; i++)
		{
			output[5].write(aesl_tmp_18[i]);
		}

		// release memory allocation: "input_V"
		delete [] tvin_input_V;
		delete [] wrapc_stream_size_in_input_V;
		// release memory allocation: "output_0_V"
		delete [] tvout_output_0_V;
		delete [] tvin_output_0_V;
		delete [] wrapc_stream_size_out_output_0_V;
		// release memory allocation: "output_1_V"
		delete [] tvout_output_1_V;
		delete [] tvin_output_1_V;
		delete [] wrapc_stream_size_out_output_1_V;
		// release memory allocation: "output_2_V"
		delete [] tvout_output_2_V;
		delete [] tvin_output_2_V;
		delete [] wrapc_stream_size_out_output_2_V;
		// release memory allocation: "output_3_V"
		delete [] tvout_output_3_V;
		delete [] tvin_output_3_V;
		delete [] wrapc_stream_size_out_output_3_V;
		// release memory allocation: "output_4_V"
		delete [] tvout_output_4_V;
		delete [] tvin_output_4_V;
		delete [] wrapc_stream_size_out_output_4_V;
		// release memory allocation: "output_5_V"
		delete [] tvout_output_5_V;
		delete [] tvin_output_5_V;
		delete [] wrapc_stream_size_out_output_5_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

