#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("image_V_dout", 8, hls_in, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("image_V_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("image_V_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("weights_address0", 5, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("weights_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("weights_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("weights_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("weights_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("weights_address1", 5, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("weights_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("weights_d1", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("weights_q1", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("weights_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("conv_output_V_din", 32, hls_out, 2, "ap_fifo", "fifo_data", 1),
	Port_Property("conv_output_V_full_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("conv_output_V_write", 1, hls_out, 2, "ap_fifo", "fifo_update", 1),
	Port_Property("done", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("done_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "convolve";
